/* tslint:disable */
/* eslint-disable */
/**
 * Geometry Backend API v2
 * The ShapeDiver Geometry Backend system is used to: * host Grasshopper models in a secure, reliable, scalable, and performant way, * run computations of Grasshopper models, * and cache and output the results of computations and exports.
 *
 * The version of the OpenAPI document: 2.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import { BaseAPI } from '../../base';
import type {
    ReqCreditMetrics,
    ResError,
    ResGetCreditMetrics,
    ResGetModelOrganizationCreditMetrics,
    ResGetModelUserCreditMetrics,
    ResGetOrganizationCreditMetrics,
    ResGetUserCreditMetrics,
} from '../models/index';

export interface GetCreditMetricsRequest {
    reqCreditMetrics: ReqCreditMetrics;
}

export interface GetModelOrganizationCreditMetricsRequest {
    timestamp: string;
    orgId: string;
}

export interface GetModelUserCreditMetricsRequest {
    timestamp: string;
    userId: string;
}

export interface GetOrganizationCreditMetricsRequest {
    timestamp: string;
}

export interface GetUserCreditMetricsRequest {
    timestamp: string;
}

/**
 * 
 */
export class AnalyticsApi extends BaseAPI {

    /**
     * Creates request options for getCreditMetrics without sending the request
     */
    async getCreditMetricsRequestOpts(requestParameters: GetCreditMetricsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['reqCreditMetrics'] == null) {
            throw new runtime.RequiredError(
                'reqCreditMetrics',
                'Required parameter "reqCreditMetrics" was null or undefined when calling getCreditMetrics().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v2/analytics/credit-metrics`;

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['reqCreditMetrics'],
        };
    }

    /**
     * Subject-Restriction: __backend__ - ONLY for _system-metrics_.  Permissions: * `analytics.model.get.*` - __required__.
     * Get credit metrics.
     */
    async getCreditMetricsRaw(requestParameters: GetCreditMetricsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResGetCreditMetrics>> {
        const requestOptions = await this.getCreditMetricsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Subject-Restriction: __backend__ - ONLY for _system-metrics_.  Permissions: * `analytics.model.get.*` - __required__.
     * Get credit metrics.
     */
    async getCreditMetrics(reqCreditMetrics: ReqCreditMetrics, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResGetCreditMetrics> {
        const response = await this.getCreditMetricsRaw({ reqCreditMetrics: reqCreditMetrics }, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getModelOrganizationCreditMetrics without sending the request
     */
    async getModelOrganizationCreditMetricsRequestOpts(requestParameters: GetModelOrganizationCreditMetricsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['timestamp'] == null) {
            throw new runtime.RequiredError(
                'timestamp',
                'Required parameter "timestamp" was null or undefined when calling getModelOrganizationCreditMetrics().'
            );
        }

        if (requestParameters['orgId'] == null) {
            throw new runtime.RequiredError(
                'orgId',
                'Required parameter "orgId" was null or undefined when calling getModelOrganizationCreditMetrics().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v2/analytics/credit-metrics/timestamp/{timestamp}/org/{orgId}`;
        urlPath = urlPath.replace('{timestamp}', encodeURIComponent(String(requestParameters['timestamp'])));
        urlPath = urlPath.replace('{orgId}', encodeURIComponent(String(requestParameters['orgId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Permissions: * `analytics.model.get.*` - __required__.
     * Get model credit metrics of the organization at timestamp.
     */
    async getModelOrganizationCreditMetricsRaw(requestParameters: GetModelOrganizationCreditMetricsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResGetModelOrganizationCreditMetrics>> {
        const requestOptions = await this.getModelOrganizationCreditMetricsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Permissions: * `analytics.model.get.*` - __required__.
     * Get model credit metrics of the organization at timestamp.
     */
    async getModelOrganizationCreditMetrics(timestamp: string, orgId: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResGetModelOrganizationCreditMetrics> {
        const response = await this.getModelOrganizationCreditMetricsRaw({ timestamp: timestamp, orgId: orgId }, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getModelUserCreditMetrics without sending the request
     */
    async getModelUserCreditMetricsRequestOpts(requestParameters: GetModelUserCreditMetricsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['timestamp'] == null) {
            throw new runtime.RequiredError(
                'timestamp',
                'Required parameter "timestamp" was null or undefined when calling getModelUserCreditMetrics().'
            );
        }

        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling getModelUserCreditMetrics().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v2/analytics/credit-metrics/timestamp/{timestamp}/user/{userId}`;
        urlPath = urlPath.replace('{timestamp}', encodeURIComponent(String(requestParameters['timestamp'])));
        urlPath = urlPath.replace('{userId}', encodeURIComponent(String(requestParameters['userId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Permissions: * `analytics.model.get.*` - __required__.
     * Get model credit metrics of the user at timestamp.
     */
    async getModelUserCreditMetricsRaw(requestParameters: GetModelUserCreditMetricsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResGetModelUserCreditMetrics>> {
        const requestOptions = await this.getModelUserCreditMetricsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Permissions: * `analytics.model.get.*` - __required__.
     * Get model credit metrics of the user at timestamp.
     */
    async getModelUserCreditMetrics(timestamp: string, userId: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResGetModelUserCreditMetrics> {
        const response = await this.getModelUserCreditMetricsRaw({ timestamp: timestamp, userId: userId }, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getOrganizationCreditMetrics without sending the request
     */
    async getOrganizationCreditMetricsRequestOpts(requestParameters: GetOrganizationCreditMetricsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['timestamp'] == null) {
            throw new runtime.RequiredError(
                'timestamp',
                'Required parameter "timestamp" was null or undefined when calling getOrganizationCreditMetrics().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v2/analytics/credit-metrics/timestamp/{timestamp}/org`;
        urlPath = urlPath.replace('{timestamp}', encodeURIComponent(String(requestParameters['timestamp'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Subject-Restriction: __backend__.  Permissions: * `analytics.model.get.*` - __required__.
     * Get credit metrics of all organizations with users active at timestamp.
     */
    async getOrganizationCreditMetricsRaw(requestParameters: GetOrganizationCreditMetricsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResGetOrganizationCreditMetrics>> {
        const requestOptions = await this.getOrganizationCreditMetricsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Subject-Restriction: __backend__.  Permissions: * `analytics.model.get.*` - __required__.
     * Get credit metrics of all organizations with users active at timestamp.
     */
    async getOrganizationCreditMetrics(timestamp: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResGetOrganizationCreditMetrics> {
        const response = await this.getOrganizationCreditMetricsRaw({ timestamp: timestamp }, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getUserCreditMetrics without sending the request
     */
    async getUserCreditMetricsRequestOpts(requestParameters: GetUserCreditMetricsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['timestamp'] == null) {
            throw new runtime.RequiredError(
                'timestamp',
                'Required parameter "timestamp" was null or undefined when calling getUserCreditMetrics().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v2/analytics/credit-metrics/timestamp/{timestamp}/user`;
        urlPath = urlPath.replace('{timestamp}', encodeURIComponent(String(requestParameters['timestamp'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Subject-Restriction: __backend__.  Permissions: * `analytics.model.get.*` - __required__.
     * Get credit metrics of all users active at timestamp.
     */
    async getUserCreditMetricsRaw(requestParameters: GetUserCreditMetricsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResGetUserCreditMetrics>> {
        const requestOptions = await this.getUserCreditMetricsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Subject-Restriction: __backend__.  Permissions: * `analytics.model.get.*` - __required__.
     * Get credit metrics of all users active at timestamp.
     */
    async getUserCreditMetrics(timestamp: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResGetUserCreditMetrics> {
        const response = await this.getUserCreditMetricsRaw({ timestamp: timestamp }, initOverrides);
        return await response.value();
    }

}
