/* tslint:disable */
/* eslint-disable */
/**
 * Geometry Backend API v2
 * The ShapeDiver Geometry Backend system is used to: * host Grasshopper models in a secure, reliable, scalable, and performant way, * run computations of Grasshopper models, * and cache and output the results of computations and exports.
 *
 * The version of the OpenAPI document: 2.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import { BaseAPI } from '../../base';
import type {
    ResError,
} from '../models/index';

export interface DownloadArSceneGltfRequest {
    sceneId: string;
}

export interface DownloadArSceneUsdzRequest {
    sceneId: string;
}

export interface GetArSceneMetadataRequest {
    sceneId: string;
}

/**
 * 
 */
export class ArSceneApi extends BaseAPI {

    /**
     * Creates request options for downloadArSceneGltf without sending the request
     */
    async downloadArSceneGltfRequestOpts(requestParameters: DownloadArSceneGltfRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['sceneId'] == null) {
            throw new runtime.RequiredError(
                'sceneId',
                'Required parameter "sceneId" was null or undefined when calling downloadArSceneGltf().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v2/ar-scene/{sceneId}/gltf`;
        urlPath = urlPath.replace('{sceneId}', encodeURIComponent(String(requestParameters['sceneId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Downloads the glTF asset of an AR scene or a Model-State that is linked to an AR scene.
     */
    async downloadArSceneGltfRaw(requestParameters: DownloadArSceneGltfRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Blob>> {
        const requestOptions = await this.downloadArSceneGltfRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.BlobApiResponse(response);
    }

    /**
     * Downloads the glTF asset of an AR scene or a Model-State that is linked to an AR scene.
     */
    async downloadArSceneGltf(sceneId: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Blob> {
        const response = await this.downloadArSceneGltfRaw({ sceneId: sceneId }, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for downloadArSceneUsdz without sending the request
     */
    async downloadArSceneUsdzRequestOpts(requestParameters: DownloadArSceneUsdzRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['sceneId'] == null) {
            throw new runtime.RequiredError(
                'sceneId',
                'Required parameter "sceneId" was null or undefined when calling downloadArSceneUsdz().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v2/ar-scene/{sceneId}/usdz`;
        urlPath = urlPath.replace('{sceneId}', encodeURIComponent(String(requestParameters['sceneId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Downloads the USDZ asset of an AR scene or a Model-State that is linked to an AR scene.
     */
    async downloadArSceneUsdzRaw(requestParameters: DownloadArSceneUsdzRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Blob>> {
        const requestOptions = await this.downloadArSceneUsdzRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.BlobApiResponse(response);
    }

    /**
     * Downloads the USDZ asset of an AR scene or a Model-State that is linked to an AR scene.
     */
    async downloadArSceneUsdz(sceneId: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Blob> {
        const response = await this.downloadArSceneUsdzRaw({ sceneId: sceneId }, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getArSceneMetadata without sending the request
     */
    async getArSceneMetadataRequestOpts(requestParameters: GetArSceneMetadataRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['sceneId'] == null) {
            throw new runtime.RequiredError(
                'sceneId',
                'Required parameter "sceneId" was null or undefined when calling getArSceneMetadata().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v2/ar-scene/{sceneId}`;
        urlPath = urlPath.replace('{sceneId}', encodeURIComponent(String(requestParameters['sceneId'])));

        return {
            path: urlPath,
            method: 'HEAD',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Verifies whether an AR scene exists or if a Model-State is linked to an AR scene.
     */
    async getArSceneMetadataRaw(requestParameters: GetArSceneMetadataRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.getArSceneMetadataRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Verifies whether an AR scene exists or if a Model-State is linked to an AR scene.
     */
    async getArSceneMetadata(sceneId: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.getArSceneMetadataRaw({ sceneId: sceneId }, initOverrides);
    }

}
