/* tslint:disable */
/* eslint-disable */
/**
 * Geometry Backend API v2
 * The ShapeDiver Geometry Backend system is used to: * host Grasshopper models in a secure, reliable, scalable, and performant way, * run computations of Grasshopper models, * and cache and output the results of computations and exports.
 *
 * The version of the OpenAPI document: 2.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import { BaseAPI } from '../../base';
import type {
    ResError,
} from '../models/index';

export interface DownloadAssetRequest {
    assetDataEncrypted: string;
}

export interface DownloadExportRequest {
    sessionId: string;
    assetDataEncrypted: string;
}

export interface DownloadGltfRequest {
    sessionId: string;
    assetDataEncrypted: string;
}

export interface DownloadImageRequest {
    sessionId: string;
    url: string;
}

export interface DownloadOutputRequest {
    sessionId: string;
    assetDataEncrypted: string;
}

export interface DownloadTextureRequest {
    sessionId: string;
    assetDataEncrypted: string;
}

export interface DownloadUsdzRequest {
    sessionId: string;
    assetDataEncrypted: string;
}

/**
 * 
 */
export class AssetsApi extends BaseAPI {

    /**
     * Creates request options for downloadAsset without sending the request
     */
    async downloadAssetRequestOpts(requestParameters: DownloadAssetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['assetDataEncrypted'] == null) {
            throw new runtime.RequiredError(
                'assetDataEncrypted',
                'Required parameter "assetDataEncrypted" was null or undefined when calling downloadAsset().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v2/download/{assetDataEncrypted}`;
        urlPath = urlPath.replace('{assetDataEncrypted}', encodeURIComponent(String(requestParameters['assetDataEncrypted'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Download an asset without a session (can be used via an URL in an email).
     */
    async downloadAssetRaw(requestParameters: DownloadAssetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Blob>> {
        const requestOptions = await this.downloadAssetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.BlobApiResponse(response);
    }

    /**
     * Download an asset without a session (can be used via an URL in an email).
     */
    async downloadAsset(assetDataEncrypted: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Blob> {
        const response = await this.downloadAssetRaw({ assetDataEncrypted: assetDataEncrypted }, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for downloadExport without sending the request
     */
    async downloadExportRequestOpts(requestParameters: DownloadExportRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['sessionId'] == null) {
            throw new runtime.RequiredError(
                'sessionId',
                'Required parameter "sessionId" was null or undefined when calling downloadExport().'
            );
        }

        if (requestParameters['assetDataEncrypted'] == null) {
            throw new runtime.RequiredError(
                'assetDataEncrypted',
                'Required parameter "assetDataEncrypted" was null or undefined when calling downloadExport().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v2/session/{sessionId}/export/{assetDataEncrypted}`;
        urlPath = urlPath.replace('{sessionId}', encodeURIComponent(String(requestParameters['sessionId'])));
        urlPath = urlPath.replace('{assetDataEncrypted}', encodeURIComponent(String(requestParameters['assetDataEncrypted'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Download a single export.
     */
    async downloadExportRaw(requestParameters: DownloadExportRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Blob>> {
        const requestOptions = await this.downloadExportRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.BlobApiResponse(response);
    }

    /**
     * Download a single export.
     */
    async downloadExport(sessionId: string, assetDataEncrypted: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Blob> {
        const response = await this.downloadExportRaw({ sessionId: sessionId, assetDataEncrypted: assetDataEncrypted }, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for downloadGltf without sending the request
     */
    async downloadGltfRequestOpts(requestParameters: DownloadGltfRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['sessionId'] == null) {
            throw new runtime.RequiredError(
                'sessionId',
                'Required parameter "sessionId" was null or undefined when calling downloadGltf().'
            );
        }

        if (requestParameters['assetDataEncrypted'] == null) {
            throw new runtime.RequiredError(
                'assetDataEncrypted',
                'Required parameter "assetDataEncrypted" was null or undefined when calling downloadGltf().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v2/session/{sessionId}/gltf/{assetDataEncrypted}`;
        urlPath = urlPath.replace('{sessionId}', encodeURIComponent(String(requestParameters['sessionId'])));
        urlPath = urlPath.replace('{assetDataEncrypted}', encodeURIComponent(String(requestParameters['assetDataEncrypted'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Download a glTF file.
     */
    async downloadGltfRaw(requestParameters: DownloadGltfRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Blob>> {
        const requestOptions = await this.downloadGltfRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.BlobApiResponse(response);
    }

    /**
     * Download a glTF file.
     */
    async downloadGltf(sessionId: string, assetDataEncrypted: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Blob> {
        const response = await this.downloadGltfRaw({ sessionId: sessionId, assetDataEncrypted: assetDataEncrypted }, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for downloadImage without sending the request
     */
    async downloadImageRequestOpts(requestParameters: DownloadImageRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['sessionId'] == null) {
            throw new runtime.RequiredError(
                'sessionId',
                'Required parameter "sessionId" was null or undefined when calling downloadImage().'
            );
        }

        if (requestParameters['url'] == null) {
            throw new runtime.RequiredError(
                'url',
                'Required parameter "url" was null or undefined when calling downloadImage().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['url'] != null) {
            queryParameters['url'] = requestParameters['url'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v2/session/{sessionId}/image`;
        urlPath = urlPath.replace('{sessionId}', encodeURIComponent(String(requestParameters['sessionId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Download an image.
     */
    async downloadImageRaw(requestParameters: DownloadImageRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Blob>> {
        const requestOptions = await this.downloadImageRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.BlobApiResponse(response);
    }

    /**
     * Download an image.
     */
    async downloadImage(sessionId: string, url: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Blob> {
        const response = await this.downloadImageRaw({ sessionId: sessionId, url: url }, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for downloadOutput without sending the request
     */
    async downloadOutputRequestOpts(requestParameters: DownloadOutputRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['sessionId'] == null) {
            throw new runtime.RequiredError(
                'sessionId',
                'Required parameter "sessionId" was null or undefined when calling downloadOutput().'
            );
        }

        if (requestParameters['assetDataEncrypted'] == null) {
            throw new runtime.RequiredError(
                'assetDataEncrypted',
                'Required parameter "assetDataEncrypted" was null or undefined when calling downloadOutput().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v2/session/{sessionId}/output/{assetDataEncrypted}`;
        urlPath = urlPath.replace('{sessionId}', encodeURIComponent(String(requestParameters['sessionId'])));
        urlPath = urlPath.replace('{assetDataEncrypted}', encodeURIComponent(String(requestParameters['assetDataEncrypted'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Download a single output.
     */
    async downloadOutputRaw(requestParameters: DownloadOutputRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Blob>> {
        const requestOptions = await this.downloadOutputRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.BlobApiResponse(response);
    }

    /**
     * Download a single output.
     */
    async downloadOutput(sessionId: string, assetDataEncrypted: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Blob> {
        const response = await this.downloadOutputRaw({ sessionId: sessionId, assetDataEncrypted: assetDataEncrypted }, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for downloadTexture without sending the request
     */
    async downloadTextureRequestOpts(requestParameters: DownloadTextureRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['sessionId'] == null) {
            throw new runtime.RequiredError(
                'sessionId',
                'Required parameter "sessionId" was null or undefined when calling downloadTexture().'
            );
        }

        if (requestParameters['assetDataEncrypted'] == null) {
            throw new runtime.RequiredError(
                'assetDataEncrypted',
                'Required parameter "assetDataEncrypted" was null or undefined when calling downloadTexture().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v2/session/{sessionId}/texture/{assetDataEncrypted}`;
        urlPath = urlPath.replace('{sessionId}', encodeURIComponent(String(requestParameters['sessionId'])));
        urlPath = urlPath.replace('{assetDataEncrypted}', encodeURIComponent(String(requestParameters['assetDataEncrypted'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Download a single texture.
     */
    async downloadTextureRaw(requestParameters: DownloadTextureRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Blob>> {
        const requestOptions = await this.downloadTextureRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.BlobApiResponse(response);
    }

    /**
     * Download a single texture.
     */
    async downloadTexture(sessionId: string, assetDataEncrypted: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Blob> {
        const response = await this.downloadTextureRaw({ sessionId: sessionId, assetDataEncrypted: assetDataEncrypted }, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for downloadUsdz without sending the request
     */
    async downloadUsdzRequestOpts(requestParameters: DownloadUsdzRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['sessionId'] == null) {
            throw new runtime.RequiredError(
                'sessionId',
                'Required parameter "sessionId" was null or undefined when calling downloadUsdz().'
            );
        }

        if (requestParameters['assetDataEncrypted'] == null) {
            throw new runtime.RequiredError(
                'assetDataEncrypted',
                'Required parameter "assetDataEncrypted" was null or undefined when calling downloadUsdz().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v2/session/{sessionId}/usdz/{assetDataEncrypted}`;
        urlPath = urlPath.replace('{sessionId}', encodeURIComponent(String(requestParameters['sessionId'])));
        urlPath = urlPath.replace('{assetDataEncrypted}', encodeURIComponent(String(requestParameters['assetDataEncrypted'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Download a USDZ file.
     */
    async downloadUsdzRaw(requestParameters: DownloadUsdzRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResError>> {
        const requestOptions = await this.downloadUsdzRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Download a USDZ file.
     */
    async downloadUsdz(sessionId: string, assetDataEncrypted: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResError> {
        const response = await this.downloadUsdzRaw({ sessionId: sessionId, assetDataEncrypted: assetDataEncrypted }, initOverrides);
        return await response.value();
    }

}
