/* tslint:disable */
/* eslint-disable */
/**
 * Geometry Backend API v2
 * The ShapeDiver Geometry Backend system is used to: * host Grasshopper models in a secure, reliable, scalable, and performant way, * run computations of Grasshopper models, * and cache and output the results of computations and exports.
 *
 * The version of the OpenAPI document: 2.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import { BaseAPI } from '../../base';
import type {
    ResError,
} from '../models/index';

/**
 * 
 */
export class AuthApi extends BaseAPI {

    /**
     * Creates request options for getJsonWebKeySets without sending the request
     */
    async getJsonWebKeySetsRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/.well-known/jwks.json`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get the public keys of the JSON Web Key Set.
     */
    async getJsonWebKeySetsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        const requestOptions = await this.getJsonWebKeySetsRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Get the public keys of the JSON Web Key Set.
     */
    async getJsonWebKeySets(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.getJsonWebKeySetsRaw(initOverrides);
        return await response.value();
    }

}
