/* tslint:disable */
/* eslint-disable */
/**
 * Geometry Backend API v2
 * The ShapeDiver Geometry Backend system is used to: * host Grasshopper models in a secure, reliable, scalable, and performant way, * run computations of Grasshopper models, * and cache and output the results of computations and exports.
 *
 * The version of the OpenAPI document: 2.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import { BaseAPI } from '../../base';
import type {
    ReqAuthorizationGroup,
    ResCreateAuthorizationGroup,
    ResError,
} from '../models/index';

export interface CreateAuthorizationGroupRequest {
    reqAuthorizationGroup: ReqAuthorizationGroup;
}

/**
 * 
 */
export class AuthGroupApi extends BaseAPI {

    /**
     * Creates request options for createAuthorizationGroup without sending the request
     */
    async createAuthorizationGroupRequestOpts(requestParameters: CreateAuthorizationGroupRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['reqAuthorizationGroup'] == null) {
            throw new runtime.RequiredError(
                'reqAuthorizationGroup',
                'Required parameter "reqAuthorizationGroup" was null or undefined when calling createAuthorizationGroup().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v2/auth_group`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['reqAuthorizationGroup'],
        };
    }

    /**
     * Subject-Restriction: __backend__.  Permissions: * `auth_group.create` - __required__.
     * Create new authorization group.
     */
    async createAuthorizationGroupRaw(requestParameters: CreateAuthorizationGroupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResCreateAuthorizationGroup>> {
        const requestOptions = await this.createAuthorizationGroupRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Subject-Restriction: __backend__.  Permissions: * `auth_group.create` - __required__.
     * Create new authorization group.
     */
    async createAuthorizationGroup(reqAuthorizationGroup: ReqAuthorizationGroup, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResCreateAuthorizationGroup> {
        const response = await this.createAuthorizationGroupRaw({ reqAuthorizationGroup: reqAuthorizationGroup }, initOverrides);
        return await response.value();
    }

}
