/* tslint:disable */
/* eslint-disable */
/**
 * Geometry Backend API v2
 * The ShapeDiver Geometry Backend system is used to: * host Grasshopper models in a secure, reliable, scalable, and performant way, * run computations of Grasshopper models, * and cache and output the results of computations and exports.
 *
 * The version of the OpenAPI document: 2.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import { BaseAPI } from '../../base';
import type {
    QueryComputationStatus,
    ReqExport,
    ReqExportDefinitions,
    ReqExportOrCache,
    ResComputeExports,
    ResError,
    ResGetCachedExports,
    ResListExportVersions,
    ResUpdateExportDefinitions,
} from '../models/index';

export interface ComputeExportsRequest {
    sessionId: string;
    reqExport: ReqExport;
    ignoreUnknownParams?: boolean;
}

export interface GetCachedExportsRequest {
    sessionId: string;
    reqExportOrCache: ReqExportOrCache;
}

export interface ListExportVersionsRequest {
    sessionId: string;
    exportId: string;
    statusComputation?: QueryComputationStatus;
    statusCollect?: QueryComputationStatus;
    offset?: string;
}

export interface UpdateExportDefinitionsRequest {
    modelId: string;
    reqExportDefinitions: ReqExportDefinitions;
}

/**
 * 
 */
export class ExportApi extends BaseAPI {

    /**
     * Creates request options for computeExports without sending the request
     */
    async computeExportsRequestOpts(requestParameters: ComputeExportsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['sessionId'] == null) {
            throw new runtime.RequiredError(
                'sessionId',
                'Required parameter "sessionId" was null or undefined when calling computeExports().'
            );
        }

        if (requestParameters['reqExport'] == null) {
            throw new runtime.RequiredError(
                'reqExport',
                'Required parameter "reqExport" was null or undefined when calling computeExports().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['ignoreUnknownParams'] != null) {
            queryParameters['ignoreUnknownParams'] = requestParameters['ignoreUnknownParams'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v2/session/{sessionId}/export`;
        urlPath = urlPath.replace('{sessionId}', encodeURIComponent(String(requestParameters['sessionId'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['reqExport'],
        };
    }

    /**
     * Permissions: * `compute.export.*` - __required__. * `compute.output.*` - __required__ when _outputs_ are requested.
     * Compute a Grasshopper exports for given parameter values.
     */
    async computeExportsRaw(requestParameters: ComputeExportsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResComputeExports>> {
        const requestOptions = await this.computeExportsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Permissions: * `compute.export.*` - __required__. * `compute.output.*` - __required__ when _outputs_ are requested.
     * Compute a Grasshopper exports for given parameter values.
     */
    async computeExports(sessionId: string, reqExport: ReqExport, ignoreUnknownParams?: boolean, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResComputeExports> {
        const response = await this.computeExportsRaw({ sessionId: sessionId, reqExport: reqExport, ignoreUnknownParams: ignoreUnknownParams }, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getCachedExports without sending the request
     */
    async getCachedExportsRequestOpts(requestParameters: GetCachedExportsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['sessionId'] == null) {
            throw new runtime.RequiredError(
                'sessionId',
                'Required parameter "sessionId" was null or undefined when calling getCachedExports().'
            );
        }

        if (requestParameters['reqExportOrCache'] == null) {
            throw new runtime.RequiredError(
                'reqExportOrCache',
                'Required parameter "reqExportOrCache" was null or undefined when calling getCachedExports().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v2/session/{sessionId}/export/cache`;
        urlPath = urlPath.replace('{sessionId}', encodeURIComponent(String(requestParameters['sessionId'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['reqExportOrCache'],
        };
    }

    /**
     * Permissions: * `cache.export.get.*` - __required__. * `cache.output.get.*` - __required__ when _outputs_ are requested.
     * Get Export from cache / check if computation is done.
     */
    async getCachedExportsRaw(requestParameters: GetCachedExportsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResGetCachedExports>> {
        const requestOptions = await this.getCachedExportsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Permissions: * `cache.export.get.*` - __required__. * `cache.output.get.*` - __required__ when _outputs_ are requested.
     * Get Export from cache / check if computation is done.
     */
    async getCachedExports(sessionId: string, reqExportOrCache: ReqExportOrCache, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResGetCachedExports> {
        const response = await this.getCachedExportsRaw({ sessionId: sessionId, reqExportOrCache: reqExportOrCache }, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listExportVersions without sending the request
     */
    async listExportVersionsRequestOpts(requestParameters: ListExportVersionsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['sessionId'] == null) {
            throw new runtime.RequiredError(
                'sessionId',
                'Required parameter "sessionId" was null or undefined when calling listExportVersions().'
            );
        }

        if (requestParameters['exportId'] == null) {
            throw new runtime.RequiredError(
                'exportId',
                'Required parameter "exportId" was null or undefined when calling listExportVersions().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['statusComputation'] != null) {
            queryParameters['statusComputation'] = requestParameters['statusComputation'];
        }

        if (requestParameters['statusCollect'] != null) {
            queryParameters['statusCollect'] = requestParameters['statusCollect'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v2/session/{sessionId}/export/{exportId}/list`;
        urlPath = urlPath.replace('{sessionId}', encodeURIComponent(String(requestParameters['sessionId'])));
        urlPath = urlPath.replace('{exportId}', encodeURIComponent(String(requestParameters['exportId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Permissions: * `cache.export.list.*` - __required__.
     * List export versions.
     */
    async listExportVersionsRaw(requestParameters: ListExportVersionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResListExportVersions>> {
        const requestOptions = await this.listExportVersionsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Permissions: * `cache.export.list.*` - __required__.
     * List export versions.
     */
    async listExportVersions(sessionId: string, exportId: string, statusComputation?: QueryComputationStatus, statusCollect?: QueryComputationStatus, offset?: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResListExportVersions> {
        const response = await this.listExportVersionsRaw({ sessionId: sessionId, exportId: exportId, statusComputation: statusComputation, statusCollect: statusCollect, offset: offset }, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateExportDefinitions without sending the request
     */
    async updateExportDefinitionsRequestOpts(requestParameters: UpdateExportDefinitionsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['modelId'] == null) {
            throw new runtime.RequiredError(
                'modelId',
                'Required parameter "modelId" was null or undefined when calling updateExportDefinitions().'
            );
        }

        if (requestParameters['reqExportDefinitions'] == null) {
            throw new runtime.RequiredError(
                'reqExportDefinitions',
                'Required parameter "reqExportDefinitions" was null or undefined when calling updateExportDefinitions().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v2/model/{modelId}/export`;
        urlPath = urlPath.replace('{modelId}', encodeURIComponent(String(requestParameters['modelId'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['reqExportDefinitions'],
        };
    }

    /**
     * Permissions: * `set.export.ui` - __required__.
     * Update definition of exports.
     */
    async updateExportDefinitionsRaw(requestParameters: UpdateExportDefinitionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResUpdateExportDefinitions>> {
        const requestOptions = await this.updateExportDefinitionsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Permissions: * `set.export.ui` - __required__.
     * Update definition of exports.
     */
    async updateExportDefinitions(modelId: string, reqExportDefinitions: ReqExportDefinitions, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResUpdateExportDefinitions> {
        const response = await this.updateExportDefinitionsRaw({ modelId: modelId, reqExportDefinitions: reqExportDefinitions }, initOverrides);
        return await response.value();
    }

}
