/* tslint:disable */
/* eslint-disable */
/**
 * Geometry Backend API v2
 * The ShapeDiver Geometry Backend system is used to: * host Grasshopper models in a secure, reliable, scalable, and performant way, * run computations of Grasshopper models, * and cache and output the results of computations and exports.
 *
 * The version of the OpenAPI document: 2.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import { BaseAPI } from '../../base';
import type {
    ReqFileUpload,
    ResDeleteFile,
    ResError,
    ResListFiles,
    ResUploadFile,
} from '../models/index';

export interface DeleteFileRequest {
    sessionId: string;
    paramId: string;
    fileId: string;
}

export interface DownloadFileRequest {
    sessionId: string;
    paramId: string;
    fileId: string;
}

export interface GetFileMetadataRequest {
    sessionId: string;
    paramId: string;
    fileId: string;
}

export interface ListFilesRequest {
    sessionId: string;
    paramId: string;
    offset?: string;
}

export interface UploadFileRequest {
    sessionId: string;
    reqFileUpload: ReqFileUpload;
}

/**
 * 
 */
export class FileApi extends BaseAPI {

    /**
     * Creates request options for deleteFile without sending the request
     */
    async deleteFileRequestOpts(requestParameters: DeleteFileRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['sessionId'] == null) {
            throw new runtime.RequiredError(
                'sessionId',
                'Required parameter "sessionId" was null or undefined when calling deleteFile().'
            );
        }

        if (requestParameters['paramId'] == null) {
            throw new runtime.RequiredError(
                'paramId',
                'Required parameter "paramId" was null or undefined when calling deleteFile().'
            );
        }

        if (requestParameters['fileId'] == null) {
            throw new runtime.RequiredError(
                'fileId',
                'Required parameter "fileId" was null or undefined when calling deleteFile().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v2/session/{sessionId}/file/{paramId}/{fileId}`;
        urlPath = urlPath.replace('{sessionId}', encodeURIComponent(String(requestParameters['sessionId'])));
        urlPath = urlPath.replace('{paramId}', encodeURIComponent(String(requestParameters['paramId'])));
        urlPath = urlPath.replace('{fileId}', encodeURIComponent(String(requestParameters['fileId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Permissions: * `asset.file.delete.*` - __required__.
     * Delete a file-asset.
     */
    async deleteFileRaw(requestParameters: DeleteFileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResDeleteFile>> {
        const requestOptions = await this.deleteFileRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Permissions: * `asset.file.delete.*` - __required__.
     * Delete a file-asset.
     */
    async deleteFile(sessionId: string, paramId: string, fileId: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResDeleteFile> {
        const response = await this.deleteFileRaw({ sessionId: sessionId, paramId: paramId, fileId: fileId }, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for downloadFile without sending the request
     */
    async downloadFileRequestOpts(requestParameters: DownloadFileRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['sessionId'] == null) {
            throw new runtime.RequiredError(
                'sessionId',
                'Required parameter "sessionId" was null or undefined when calling downloadFile().'
            );
        }

        if (requestParameters['paramId'] == null) {
            throw new runtime.RequiredError(
                'paramId',
                'Required parameter "paramId" was null or undefined when calling downloadFile().'
            );
        }

        if (requestParameters['fileId'] == null) {
            throw new runtime.RequiredError(
                'fileId',
                'Required parameter "fileId" was null or undefined when calling downloadFile().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v2/session/{sessionId}/file/{paramId}/{fileId}`;
        urlPath = urlPath.replace('{sessionId}', encodeURIComponent(String(requestParameters['sessionId'])));
        urlPath = urlPath.replace('{paramId}', encodeURIComponent(String(requestParameters['paramId'])));
        urlPath = urlPath.replace('{fileId}', encodeURIComponent(String(requestParameters['fileId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Permissions: * `asset.file.get.*` - __required__.
     * Download a file-asset.
     */
    async downloadFileRaw(requestParameters: DownloadFileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Blob>> {
        const requestOptions = await this.downloadFileRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.BlobApiResponse(response);
    }

    /**
     * Permissions: * `asset.file.get.*` - __required__.
     * Download a file-asset.
     */
    async downloadFile(sessionId: string, paramId: string, fileId: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Blob> {
        const response = await this.downloadFileRaw({ sessionId: sessionId, paramId: paramId, fileId: fileId }, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getFileMetadata without sending the request
     */
    async getFileMetadataRequestOpts(requestParameters: GetFileMetadataRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['sessionId'] == null) {
            throw new runtime.RequiredError(
                'sessionId',
                'Required parameter "sessionId" was null or undefined when calling getFileMetadata().'
            );
        }

        if (requestParameters['paramId'] == null) {
            throw new runtime.RequiredError(
                'paramId',
                'Required parameter "paramId" was null or undefined when calling getFileMetadata().'
            );
        }

        if (requestParameters['fileId'] == null) {
            throw new runtime.RequiredError(
                'fileId',
                'Required parameter "fileId" was null or undefined when calling getFileMetadata().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v2/session/{sessionId}/file/{paramId}/{fileId}`;
        urlPath = urlPath.replace('{sessionId}', encodeURIComponent(String(requestParameters['sessionId'])));
        urlPath = urlPath.replace('{paramId}', encodeURIComponent(String(requestParameters['paramId'])));
        urlPath = urlPath.replace('{fileId}', encodeURIComponent(String(requestParameters['fileId'])));

        return {
            path: urlPath,
            method: 'HEAD',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get information about a file-asset of a parameter.
     */
    async getFileMetadataRaw(requestParameters: GetFileMetadataRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.getFileMetadataRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Get information about a file-asset of a parameter.
     */
    async getFileMetadata(sessionId: string, paramId: string, fileId: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.getFileMetadataRaw({ sessionId: sessionId, paramId: paramId, fileId: fileId }, initOverrides);
    }

    /**
     * Creates request options for listFiles without sending the request
     */
    async listFilesRequestOpts(requestParameters: ListFilesRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['sessionId'] == null) {
            throw new runtime.RequiredError(
                'sessionId',
                'Required parameter "sessionId" was null or undefined when calling listFiles().'
            );
        }

        if (requestParameters['paramId'] == null) {
            throw new runtime.RequiredError(
                'paramId',
                'Required parameter "paramId" was null or undefined when calling listFiles().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v2/session/{sessionId}/file/{paramId}/list`;
        urlPath = urlPath.replace('{sessionId}', encodeURIComponent(String(requestParameters['sessionId'])));
        urlPath = urlPath.replace('{paramId}', encodeURIComponent(String(requestParameters['paramId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Permissions: * `asset.file.list.*` - __required__.
     * List all file-assets of a parameter.
     */
    async listFilesRaw(requestParameters: ListFilesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResListFiles>> {
        const requestOptions = await this.listFilesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Permissions: * `asset.file.list.*` - __required__.
     * List all file-assets of a parameter.
     */
    async listFiles(sessionId: string, paramId: string, offset?: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResListFiles> {
        const response = await this.listFilesRaw({ sessionId: sessionId, paramId: paramId, offset: offset }, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for uploadFile without sending the request
     */
    async uploadFileRequestOpts(requestParameters: UploadFileRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['sessionId'] == null) {
            throw new runtime.RequiredError(
                'sessionId',
                'Required parameter "sessionId" was null or undefined when calling uploadFile().'
            );
        }

        if (requestParameters['reqFileUpload'] == null) {
            throw new runtime.RequiredError(
                'reqFileUpload',
                'Required parameter "reqFileUpload" was null or undefined when calling uploadFile().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v2/session/{sessionId}/file/upload`;
        urlPath = urlPath.replace('{sessionId}', encodeURIComponent(String(requestParameters['sessionId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['reqFileUpload'],
        };
    }

    /**
     * Permissions: * `asset.file.create.*` - __required__.
     * Request upload URL for a file-asset.
     */
    async uploadFileRaw(requestParameters: UploadFileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResUploadFile>> {
        const requestOptions = await this.uploadFileRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Permissions: * `asset.file.create.*` - __required__.
     * Request upload URL for a file-asset.
     */
    async uploadFile(sessionId: string, reqFileUpload: ReqFileUpload, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResUploadFile> {
        const response = await this.uploadFileRaw({ sessionId: sessionId, reqFileUpload: reqFileUpload }, initOverrides);
        return await response.value();
    }

}
