/* tslint:disable */
/* eslint-disable */
/**
 * Geometry Backend API v2
 * The ShapeDiver Geometry Backend system is used to: * host Grasshopper models in a secure, reliable, scalable, and performant way, * run computations of Grasshopper models, * and cache and output the results of computations and exports.
 *
 * The version of the OpenAPI document: 2.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import { BaseAPI } from '../../base';
import type {
    QueryGltfConversion,
    ResError,
    ResUploadGltf,
} from '../models/index';

export interface UploadGltfRequest {
    sessionId: string;
    body: Blob;
    conversion?: QueryGltfConversion;
}

/**
 * 
 */
export class GltfApi extends BaseAPI {

    /**
     * Creates request options for uploadGltf without sending the request
     */
    async uploadGltfRequestOpts(requestParameters: UploadGltfRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['sessionId'] == null) {
            throw new runtime.RequiredError(
                'sessionId',
                'Required parameter "sessionId" was null or undefined when calling uploadGltf().'
            );
        }

        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling uploadGltf().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['conversion'] != null) {
            queryParameters['conversion'] = requestParameters['conversion'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'model/gltf-binary';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v2/session/{sessionId}/gltf`;
        urlPath = urlPath.replace('{sessionId}', encodeURIComponent(String(requestParameters['sessionId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        };
    }

    /**
     * Upload and optionally convert a glTF object.
     */
    async uploadGltfRaw(requestParameters: UploadGltfRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResUploadGltf>> {
        const requestOptions = await this.uploadGltfRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Upload and optionally convert a glTF object.
     */
    async uploadGltf(sessionId: string, body: Blob, conversion?: QueryGltfConversion, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResUploadGltf> {
        const response = await this.uploadGltfRaw({ sessionId: sessionId, body: body, conversion: conversion }, initOverrides);
        return await response.value();
    }

}
