/* tslint:disable */
/* eslint-disable */
/**
 * Geometry Backend API v2
 * The ShapeDiver Geometry Backend system is used to: * host Grasshopper models in a secure, reliable, scalable, and performant way, * run computations of Grasshopper models, * and cache and output the results of computations and exports.
 *
 * The version of the OpenAPI document: 2.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import { BaseAPI } from '../../base';
import type {
    ReqLogMessage,
    ResError,
    ResLogMessage,
} from '../models/index';

export interface LogMessageRequest {
    sessionId: string;
    reqLogMessage: ReqLogMessage;
}

/**
 * 
 */
export class LogApi extends BaseAPI {

    /**
     * Creates request options for logMessage without sending the request
     */
    async logMessageRequestOpts(requestParameters: LogMessageRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['sessionId'] == null) {
            throw new runtime.RequiredError(
                'sessionId',
                'Required parameter "sessionId" was null or undefined when calling logMessage().'
            );
        }

        if (requestParameters['reqLogMessage'] == null) {
            throw new runtime.RequiredError(
                'reqLogMessage',
                'Required parameter "reqLogMessage" was null or undefined when calling logMessage().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v2/session/{sessionId}/log/message`;
        urlPath = urlPath.replace('{sessionId}', encodeURIComponent(String(requestParameters['sessionId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['reqLogMessage'],
        };
    }

    /**
     * Log message.
     */
    async logMessageRaw(requestParameters: LogMessageRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResLogMessage>> {
        const requestOptions = await this.logMessageRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Log message.
     */
    async logMessage(sessionId: string, reqLogMessage: ReqLogMessage, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResLogMessage> {
        const response = await this.logMessageRaw({ sessionId: sessionId, reqLogMessage: reqLogMessage }, initOverrides);
        return await response.value();
    }

}
