/* tslint:disable */
/* eslint-disable */
/**
 * Geometry Backend API v2
 * The ShapeDiver Geometry Backend system is used to: * host Grasshopper models in a secure, reliable, scalable, and performant way, * run computations of Grasshopper models, * and cache and output the results of computations and exports.
 *
 * The version of the OpenAPI document: 2.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import { BaseAPI } from '../../base';
import type {
    ReqModelState,
    ResCreateModelState,
    ResDeleteModelState,
    ResError,
    ResGetModelState,
    ResGetModelStateData,
    ResListModelStates,
} from '../models/index';

export interface CreateModelStateRequest {
    sessionId: string;
    reqModelState: ReqModelState;
    ignoreUnknownParams?: boolean;
}

export interface DeleteModelStateRequest {
    modelStateId: string;
}

export interface DownloadModelStateImageRequest {
    modelStateId: string;
}

export interface GetModelStateRequest {
    modelStateId: string;
}

export interface GetModelStateDataRequest {
    modelStateId: string;
}

export interface GetModelStateImageMetadataRequest {
    modelStateId: string;
}

export interface GetModelStateMetadataRequest {
    modelStateId: string;
}

export interface ListModelStatesRequest {
    modelId: string;
    offset?: string;
}

/**
 * 
 */
export class ModelStateApi extends BaseAPI {

    /**
     * Creates request options for createModelState without sending the request
     */
    async createModelStateRequestOpts(requestParameters: CreateModelStateRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['sessionId'] == null) {
            throw new runtime.RequiredError(
                'sessionId',
                'Required parameter "sessionId" was null or undefined when calling createModelState().'
            );
        }

        if (requestParameters['reqModelState'] == null) {
            throw new runtime.RequiredError(
                'reqModelState',
                'Required parameter "reqModelState" was null or undefined when calling createModelState().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['ignoreUnknownParams'] != null) {
            queryParameters['ignoreUnknownParams'] = requestParameters['ignoreUnknownParams'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v2/session/{sessionId}/model-state`;
        urlPath = urlPath.replace('{sessionId}', encodeURIComponent(String(requestParameters['sessionId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['reqModelState'],
        };
    }

    /**
     * Create new Model-State.
     */
    async createModelStateRaw(requestParameters: CreateModelStateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResCreateModelState>> {
        const requestOptions = await this.createModelStateRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Create new Model-State.
     */
    async createModelState(sessionId: string, reqModelState: ReqModelState, ignoreUnknownParams?: boolean, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResCreateModelState> {
        const response = await this.createModelStateRaw({ sessionId: sessionId, reqModelState: reqModelState, ignoreUnknownParams: ignoreUnknownParams }, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteModelState without sending the request
     */
    async deleteModelStateRequestOpts(requestParameters: DeleteModelStateRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['modelStateId'] == null) {
            throw new runtime.RequiredError(
                'modelStateId',
                'Required parameter "modelStateId" was null or undefined when calling deleteModelState().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v2/model-state/{modelStateId}`;
        urlPath = urlPath.replace('{modelStateId}', encodeURIComponent(String(requestParameters['modelStateId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Subject-Restriction: __backend__.
     * Delete a Model-State.
     */
    async deleteModelStateRaw(requestParameters: DeleteModelStateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResDeleteModelState>> {
        const requestOptions = await this.deleteModelStateRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Subject-Restriction: __backend__.
     * Delete a Model-State.
     */
    async deleteModelState(modelStateId: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResDeleteModelState> {
        const response = await this.deleteModelStateRaw({ modelStateId: modelStateId }, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for downloadModelStateImage without sending the request
     */
    async downloadModelStateImageRequestOpts(requestParameters: DownloadModelStateImageRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['modelStateId'] == null) {
            throw new runtime.RequiredError(
                'modelStateId',
                'Required parameter "modelStateId" was null or undefined when calling downloadModelStateImage().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v2/model-state/{modelStateId}/image`;
        urlPath = urlPath.replace('{modelStateId}', encodeURIComponent(String(requestParameters['modelStateId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Downloads the Model-State image.
     */
    async downloadModelStateImageRaw(requestParameters: DownloadModelStateImageRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Blob>> {
        const requestOptions = await this.downloadModelStateImageRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.BlobApiResponse(response);
    }

    /**
     * Downloads the Model-State image.
     */
    async downloadModelStateImage(modelStateId: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Blob> {
        const response = await this.downloadModelStateImageRaw({ modelStateId: modelStateId }, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getModelState without sending the request
     */
    async getModelStateRequestOpts(requestParameters: GetModelStateRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['modelStateId'] == null) {
            throw new runtime.RequiredError(
                'modelStateId',
                'Required parameter "modelStateId" was null or undefined when calling getModelState().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v2/model-state/{modelStateId}`;
        urlPath = urlPath.replace('{modelStateId}', encodeURIComponent(String(requestParameters['modelStateId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get a Model-State.
     */
    async getModelStateRaw(requestParameters: GetModelStateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResGetModelState>> {
        const requestOptions = await this.getModelStateRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Get a Model-State.
     */
    async getModelState(modelStateId: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResGetModelState> {
        const response = await this.getModelStateRaw({ modelStateId: modelStateId }, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getModelStateData without sending the request
     */
    async getModelStateDataRequestOpts(requestParameters: GetModelStateDataRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['modelStateId'] == null) {
            throw new runtime.RequiredError(
                'modelStateId',
                'Required parameter "modelStateId" was null or undefined when calling getModelStateData().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v2/model-state/{modelStateId}/data`;
        urlPath = urlPath.replace('{modelStateId}', encodeURIComponent(String(requestParameters['modelStateId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get a Model-State\'s parameter and additional data.
     */
    async getModelStateDataRaw(requestParameters: GetModelStateDataRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResGetModelStateData>> {
        const requestOptions = await this.getModelStateDataRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Get a Model-State\'s parameter and additional data.
     */
    async getModelStateData(modelStateId: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResGetModelStateData> {
        const response = await this.getModelStateDataRaw({ modelStateId: modelStateId }, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getModelStateImageMetadata without sending the request
     */
    async getModelStateImageMetadataRequestOpts(requestParameters: GetModelStateImageMetadataRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['modelStateId'] == null) {
            throw new runtime.RequiredError(
                'modelStateId',
                'Required parameter "modelStateId" was null or undefined when calling getModelStateImageMetadata().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v2/model-state/{modelStateId}/image`;
        urlPath = urlPath.replace('{modelStateId}', encodeURIComponent(String(requestParameters['modelStateId'])));

        return {
            path: urlPath,
            method: 'HEAD',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Checks if the Model-State has an image.
     */
    async getModelStateImageMetadataRaw(requestParameters: GetModelStateImageMetadataRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.getModelStateImageMetadataRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Checks if the Model-State has an image.
     */
    async getModelStateImageMetadata(modelStateId: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.getModelStateImageMetadataRaw({ modelStateId: modelStateId }, initOverrides);
    }

    /**
     * Creates request options for getModelStateMetadata without sending the request
     */
    async getModelStateMetadataRequestOpts(requestParameters: GetModelStateMetadataRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['modelStateId'] == null) {
            throw new runtime.RequiredError(
                'modelStateId',
                'Required parameter "modelStateId" was null or undefined when calling getModelStateMetadata().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v2/model-state/{modelStateId}`;
        urlPath = urlPath.replace('{modelStateId}', encodeURIComponent(String(requestParameters['modelStateId'])));

        return {
            path: urlPath,
            method: 'HEAD',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Checks the existence of a Model-State.
     */
    async getModelStateMetadataRaw(requestParameters: GetModelStateMetadataRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.getModelStateMetadataRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Checks the existence of a Model-State.
     */
    async getModelStateMetadata(modelStateId: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.getModelStateMetadataRaw({ modelStateId: modelStateId }, initOverrides);
    }

    /**
     * Creates request options for listModelStates without sending the request
     */
    async listModelStatesRequestOpts(requestParameters: ListModelStatesRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['modelId'] == null) {
            throw new runtime.RequiredError(
                'modelId',
                'Required parameter "modelId" was null or undefined when calling listModelStates().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v2/model-state/model/{modelId}/list`;
        urlPath = urlPath.replace('{modelId}', encodeURIComponent(String(requestParameters['modelId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Subject-Restriction: __backend__.
     * List Model-States of a ShapeDiver model.
     */
    async listModelStatesRaw(requestParameters: ListModelStatesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResListModelStates>> {
        const requestOptions = await this.listModelStatesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Subject-Restriction: __backend__.
     * List Model-States of a ShapeDiver model.
     */
    async listModelStates(modelId: string, offset?: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResListModelStates> {
        const response = await this.listModelStatesRaw({ modelId: modelId, offset: offset }, initOverrides);
        return await response.value();
    }

}
