/* tslint:disable */
/* eslint-disable */
/**
 * Geometry Backend API v2
 * The ShapeDiver Geometry Backend system is used to: * host Grasshopper models in a secure, reliable, scalable, and performant way, * run computations of Grasshopper models, * and cache and output the results of computations and exports.
 *
 * The version of the OpenAPI document: 2.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import { BaseAPI } from '../../base';
import type {
    QueryComputationStatisticsStatus,
    QueryComputationType,
    QueryModelStatus,
    QueryOrder,
    ReqConfigure,
    ReqCustomization,
    ReqModel,
    ReqParameterDefinitions,
    ResCleanupExports,
    ResCleanupOutputs,
    ResCleanupTextures,
    ResCreateModel,
    ResCreateModelConfig,
    ResDeleteModel,
    ResError,
    ResGetCleanupStatus,
    ResGetModel,
    ResGetModelComputations,
    ResGetModelConfig,
    ResListModels,
    ResUpdateModel,
    ResUpdateModelConfig,
    ResUpdateParameterDefaultValues,
    ResUpdateParameterDefinitions,
} from '../models/index';

export interface CleanupExportsRequest {
    modelId: string;
    untilLastSeen: string;
}

export interface CleanupOutputsRequest {
    modelId: string;
    untilLastSeen: string;
}

export interface CleanupTexturesRequest {
    modelId: string;
    untilLastSeen: string;
}

export interface CreateModelRequest {
    reqModel: ReqModel;
}

export interface CreateModelConfigRequest {
    modelId: string;
    reqConfigure: ReqConfigure;
}

export interface DeleteModelRequest {
    modelId: string;
}

export interface DownloadModelFileRequest {
    modelId: string;
}

export interface GetCleanupStatusRequest {
    modelId: string;
}

export interface GetModelRequest {
    modelId: string;
}

export interface GetModelComputationsRequest {
    modelId: string;
    order?: QueryOrder;
    timestampFrom?: string;
    timestampTo?: string;
    status?: QueryComputationStatisticsStatus;
    type?: QueryComputationType;
    limit?: number;
    strictLimit?: boolean;
    offset?: string;
}

export interface GetModelConfigRequest {
    modelId: string;
    xShapediverNoconvert?: boolean;
    xShapediverUseconfigversion?: string;
    xShapediverBuildversion?: string;
}

export interface ListModelsRequest {
    modelStatus?: QueryModelStatus;
    offset?: string;
}

export interface RestoreModelRequest {
    modelId: string;
}

export interface UpdateModelRequest {
    modelId: string;
    reqModel: ReqModel;
}

export interface UpdateModelConfigRequest {
    modelId: string;
    reqConfigure: ReqConfigure;
}

export interface UpdateParameterDefaultValuesRequest {
    modelId: string;
    reqCustomization: ReqCustomization;
    ignoreUnknownParams?: boolean;
}

export interface UpdateParameterDefinitionsRequest {
    modelId: string;
    reqParameterDefinitions: ReqParameterDefinitions;
}

/**
 * 
 */
export class ModelApi extends BaseAPI {

    /**
     * Creates request options for cleanupExports without sending the request
     */
    async cleanupExportsRequestOpts(requestParameters: CleanupExportsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['modelId'] == null) {
            throw new runtime.RequiredError(
                'modelId',
                'Required parameter "modelId" was null or undefined when calling cleanupExports().'
            );
        }

        if (requestParameters['untilLastSeen'] == null) {
            throw new runtime.RequiredError(
                'untilLastSeen',
                'Required parameter "untilLastSeen" was null or undefined when calling cleanupExports().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['untilLastSeen'] != null) {
            queryParameters['untilLastSeen'] = requestParameters['untilLastSeen'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v2/model/{modelId}/cleanup/export`;
        urlPath = urlPath.replace('{modelId}', encodeURIComponent(String(requestParameters['modelId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Permissions: * `cache.export.delete.*` - __required__.
     * Delete old export components.
     */
    async cleanupExportsRaw(requestParameters: CleanupExportsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResCleanupExports>> {
        const requestOptions = await this.cleanupExportsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Permissions: * `cache.export.delete.*` - __required__.
     * Delete old export components.
     */
    async cleanupExports(modelId: string, untilLastSeen: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResCleanupExports> {
        const response = await this.cleanupExportsRaw({ modelId: modelId, untilLastSeen: untilLastSeen }, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for cleanupOutputs without sending the request
     */
    async cleanupOutputsRequestOpts(requestParameters: CleanupOutputsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['modelId'] == null) {
            throw new runtime.RequiredError(
                'modelId',
                'Required parameter "modelId" was null or undefined when calling cleanupOutputs().'
            );
        }

        if (requestParameters['untilLastSeen'] == null) {
            throw new runtime.RequiredError(
                'untilLastSeen',
                'Required parameter "untilLastSeen" was null or undefined when calling cleanupOutputs().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['untilLastSeen'] != null) {
            queryParameters['untilLastSeen'] = requestParameters['untilLastSeen'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v2/model/{modelId}/cleanup/output`;
        urlPath = urlPath.replace('{modelId}', encodeURIComponent(String(requestParameters['modelId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Permissions: * `cache.output.delete.*` - __required__.
     * Delete old output components.
     */
    async cleanupOutputsRaw(requestParameters: CleanupOutputsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResCleanupOutputs>> {
        const requestOptions = await this.cleanupOutputsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Permissions: * `cache.output.delete.*` - __required__.
     * Delete old output components.
     */
    async cleanupOutputs(modelId: string, untilLastSeen: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResCleanupOutputs> {
        const response = await this.cleanupOutputsRaw({ modelId: modelId, untilLastSeen: untilLastSeen }, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for cleanupTextures without sending the request
     */
    async cleanupTexturesRequestOpts(requestParameters: CleanupTexturesRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['modelId'] == null) {
            throw new runtime.RequiredError(
                'modelId',
                'Required parameter "modelId" was null or undefined when calling cleanupTextures().'
            );
        }

        if (requestParameters['untilLastSeen'] == null) {
            throw new runtime.RequiredError(
                'untilLastSeen',
                'Required parameter "untilLastSeen" was null or undefined when calling cleanupTextures().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['untilLastSeen'] != null) {
            queryParameters['untilLastSeen'] = requestParameters['untilLastSeen'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v2/model/{modelId}/cleanup/texture`;
        urlPath = urlPath.replace('{modelId}', encodeURIComponent(String(requestParameters['modelId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Permissions: * `cache.texture.delete.*` - __required__.
     * Delete old texture components.
     */
    async cleanupTexturesRaw(requestParameters: CleanupTexturesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResCleanupTextures>> {
        const requestOptions = await this.cleanupTexturesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Permissions: * `cache.texture.delete.*` - __required__.
     * Delete old texture components.
     */
    async cleanupTextures(modelId: string, untilLastSeen: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResCleanupTextures> {
        const response = await this.cleanupTexturesRaw({ modelId: modelId, untilLastSeen: untilLastSeen }, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createModel without sending the request
     */
    async createModelRequestOpts(requestParameters: CreateModelRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['reqModel'] == null) {
            throw new runtime.RequiredError(
                'reqModel',
                'Required parameter "reqModel" was null or undefined when calling createModel().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v2/model`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['reqModel'],
        };
    }

    /**
     * Subject-Restriction: __backend__.  Permissions: * `create` - __required__ * `setting.auth.ticket.get.*` - optional: adds _settings.auth.ticket_ to response. * `setting.auth.token.get.*` - optional: adds _settings.auth.token_ to response. * `setting.compute.get.*` - optional: adds _settings.compute_ to response. * `file.upload` - optional: adds _file.upload_ to response if no model has already been   uploaded. * `file.download` - optional: adds _file.download_ to response. * `get.statistic.*` - optional: adds _statistic_ to response.
     * Create model.
     */
    async createModelRaw(requestParameters: CreateModelRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResCreateModel>> {
        const requestOptions = await this.createModelRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Subject-Restriction: __backend__.  Permissions: * `create` - __required__ * `setting.auth.ticket.get.*` - optional: adds _settings.auth.ticket_ to response. * `setting.auth.token.get.*` - optional: adds _settings.auth.token_ to response. * `setting.compute.get.*` - optional: adds _settings.compute_ to response. * `file.upload` - optional: adds _file.upload_ to response if no model has already been   uploaded. * `file.download` - optional: adds _file.download_ to response. * `get.statistic.*` - optional: adds _statistic_ to response.
     * Create model.
     */
    async createModel(reqModel: ReqModel, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResCreateModel> {
        const response = await this.createModelRaw({ reqModel: reqModel }, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createModelConfig without sending the request
     */
    async createModelConfigRequestOpts(requestParameters: CreateModelConfigRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['modelId'] == null) {
            throw new runtime.RequiredError(
                'modelId',
                'Required parameter "modelId" was null or undefined when calling createModelConfig().'
            );
        }

        if (requestParameters['reqConfigure'] == null) {
            throw new runtime.RequiredError(
                'reqConfigure',
                'Required parameter "reqConfigure" was null or undefined when calling createModelConfig().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v2/model/{modelId}/config`;
        urlPath = urlPath.replace('{modelId}', encodeURIComponent(String(requestParameters['modelId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['reqConfigure'],
        };
    }

    /**
     * Permissions: * `setting.viewer.set.*` - __required__.
     * Create model config.
     */
    async createModelConfigRaw(requestParameters: CreateModelConfigRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResCreateModelConfig>> {
        const requestOptions = await this.createModelConfigRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Permissions: * `setting.viewer.set.*` - __required__.
     * Create model config.
     */
    async createModelConfig(modelId: string, reqConfigure: ReqConfigure, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResCreateModelConfig> {
        const response = await this.createModelConfigRaw({ modelId: modelId, reqConfigure: reqConfigure }, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteModel without sending the request
     */
    async deleteModelRequestOpts(requestParameters: DeleteModelRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['modelId'] == null) {
            throw new runtime.RequiredError(
                'modelId',
                'Required parameter "modelId" was null or undefined when calling deleteModel().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v2/model/{modelId}`;
        urlPath = urlPath.replace('{modelId}', encodeURIComponent(String(requestParameters['modelId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Subject-Restriction: __backend__.  Permissions: * `delete.soft` - __required__.
     * Delete model.
     */
    async deleteModelRaw(requestParameters: DeleteModelRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResDeleteModel>> {
        const requestOptions = await this.deleteModelRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Subject-Restriction: __backend__.  Permissions: * `delete.soft` - __required__.
     * Delete model.
     */
    async deleteModel(modelId: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResDeleteModel> {
        const response = await this.deleteModelRaw({ modelId: modelId }, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for downloadModelFile without sending the request
     */
    async downloadModelFileRequestOpts(requestParameters: DownloadModelFileRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['modelId'] == null) {
            throw new runtime.RequiredError(
                'modelId',
                'Required parameter "modelId" was null or undefined when calling downloadModelFile().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v2/model/{modelId}/file/download`;
        urlPath = urlPath.replace('{modelId}', encodeURIComponent(String(requestParameters['modelId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Permissions: * `file.download` - __required__.
     * Download Grasshopper file.
     */
    async downloadModelFileRaw(requestParameters: DownloadModelFileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Blob>> {
        const requestOptions = await this.downloadModelFileRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.BlobApiResponse(response);
    }

    /**
     * Permissions: * `file.download` - __required__.
     * Download Grasshopper file.
     */
    async downloadModelFile(modelId: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Blob> {
        const response = await this.downloadModelFileRaw({ modelId: modelId }, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getCleanupStatus without sending the request
     */
    async getCleanupStatusRequestOpts(requestParameters: GetCleanupStatusRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['modelId'] == null) {
            throw new runtime.RequiredError(
                'modelId',
                'Required parameter "modelId" was null or undefined when calling getCleanupStatus().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v2/model/{modelId}/cleanup/status`;
        urlPath = urlPath.replace('{modelId}', encodeURIComponent(String(requestParameters['modelId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * 
     * Get the status of all running model cleanup processes.
     */
    async getCleanupStatusRaw(requestParameters: GetCleanupStatusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResGetCleanupStatus>> {
        const requestOptions = await this.getCleanupStatusRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * 
     * Get the status of all running model cleanup processes.
     */
    async getCleanupStatus(modelId: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResGetCleanupStatus> {
        const response = await this.getCleanupStatusRaw({ modelId: modelId }, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getModel without sending the request
     */
    async getModelRequestOpts(requestParameters: GetModelRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['modelId'] == null) {
            throw new runtime.RequiredError(
                'modelId',
                'Required parameter "modelId" was null or undefined when calling getModel().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v2/model/{modelId}`;
        urlPath = urlPath.replace('{modelId}', encodeURIComponent(String(requestParameters['modelId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Permissions: * `setting.auth.ticket.get.*` - optional: adds _settings.auth.ticket_. * `setting.auth.token.get.*` - optional: adds _settings.auth.token_. * `setting.compute.get.*` - optional: adds _settings.compute_. * `file.upload` - optional: adds _file.upload_. * `file.download` - optional: adds _file.download_. * `get.statistic.*` - optional: adds _statistic_. * `setting.viewer.get.*` - optional: adds _viewer_. * `get.parameter.*` - optional: adds _parameters_. * `get.output*` - optional: adds _output definitions_. * `get.export*` - optional: adds _export definitions_.
     * Get model.
     */
    async getModelRaw(requestParameters: GetModelRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResGetModel>> {
        const requestOptions = await this.getModelRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Permissions: * `setting.auth.ticket.get.*` - optional: adds _settings.auth.ticket_. * `setting.auth.token.get.*` - optional: adds _settings.auth.token_. * `setting.compute.get.*` - optional: adds _settings.compute_. * `file.upload` - optional: adds _file.upload_. * `file.download` - optional: adds _file.download_. * `get.statistic.*` - optional: adds _statistic_. * `setting.viewer.get.*` - optional: adds _viewer_. * `get.parameter.*` - optional: adds _parameters_. * `get.output*` - optional: adds _output definitions_. * `get.export*` - optional: adds _export definitions_.
     * Get model.
     */
    async getModel(modelId: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResGetModel> {
        const response = await this.getModelRaw({ modelId: modelId }, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getModelComputations without sending the request
     */
    async getModelComputationsRequestOpts(requestParameters: GetModelComputationsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['modelId'] == null) {
            throw new runtime.RequiredError(
                'modelId',
                'Required parameter "modelId" was null or undefined when calling getModelComputations().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['order'] != null) {
            queryParameters['order'] = requestParameters['order'];
        }

        if (requestParameters['timestampFrom'] != null) {
            queryParameters['timestamp_from'] = requestParameters['timestampFrom'];
        }

        if (requestParameters['timestampTo'] != null) {
            queryParameters['timestamp_to'] = requestParameters['timestampTo'];
        }

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        if (requestParameters['type'] != null) {
            queryParameters['type'] = requestParameters['type'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['strictLimit'] != null) {
            queryParameters['strict_limit'] = requestParameters['strictLimit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v2/model/{modelId}/computations`;
        urlPath = urlPath.replace('{modelId}', encodeURIComponent(String(requestParameters['modelId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Permissions: * `analytics.model.get.*` - __required__.
     * Get model computation statistics.
     */
    async getModelComputationsRaw(requestParameters: GetModelComputationsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResGetModelComputations>> {
        const requestOptions = await this.getModelComputationsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Permissions: * `analytics.model.get.*` - __required__.
     * Get model computation statistics.
     */
    async getModelComputations(modelId: string, order?: QueryOrder, timestampFrom?: string, timestampTo?: string, status?: QueryComputationStatisticsStatus, type?: QueryComputationType, limit?: number, strictLimit?: boolean, offset?: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResGetModelComputations> {
        const response = await this.getModelComputationsRaw({ modelId: modelId, order: order, timestampFrom: timestampFrom, timestampTo: timestampTo, status: status, type: type, limit: limit, strictLimit: strictLimit, offset: offset }, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getModelConfig without sending the request
     */
    async getModelConfigRequestOpts(requestParameters: GetModelConfigRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['modelId'] == null) {
            throw new runtime.RequiredError(
                'modelId',
                'Required parameter "modelId" was null or undefined when calling getModelConfig().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xShapediverNoconvert'] != null) {
            headerParameters['x-shapediver-noconvert'] = String(requestParameters['xShapediverNoconvert']);
        }

        if (requestParameters['xShapediverUseconfigversion'] != null) {
            headerParameters['x-shapediver-useconfigversion'] = String(requestParameters['xShapediverUseconfigversion']);
        }

        if (requestParameters['xShapediverBuildversion'] != null) {
            headerParameters['x-shapediver-buildversion'] = String(requestParameters['xShapediverBuildversion']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v2/model/{modelId}/config`;
        urlPath = urlPath.replace('{modelId}', encodeURIComponent(String(requestParameters['modelId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Permissions: * `setting.viewer.get.*` - __required__.
     * Get model config.
     */
    async getModelConfigRaw(requestParameters: GetModelConfigRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResGetModelConfig>> {
        const requestOptions = await this.getModelConfigRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Permissions: * `setting.viewer.get.*` - __required__.
     * Get model config.
     */
    async getModelConfig(modelId: string, xShapediverNoconvert?: boolean, xShapediverUseconfigversion?: string, xShapediverBuildversion?: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResGetModelConfig> {
        const response = await this.getModelConfigRaw({ modelId: modelId, xShapediverNoconvert: xShapediverNoconvert, xShapediverUseconfigversion: xShapediverUseconfigversion, xShapediverBuildversion: xShapediverBuildversion }, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listModels without sending the request
     */
    async listModelsRequestOpts(requestParameters: ListModelsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['modelStatus'] != null) {
            queryParameters['modelStatus'] = requestParameters['modelStatus'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v2/model/list`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Subject-Restriction: __backend__.
     * List models.
     */
    async listModelsRaw(requestParameters: ListModelsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResListModels>> {
        const requestOptions = await this.listModelsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Subject-Restriction: __backend__.
     * List models.
     */
    async listModels(modelStatus?: QueryModelStatus, offset?: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResListModels> {
        const response = await this.listModelsRaw({ modelStatus: modelStatus, offset: offset }, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for restoreModel without sending the request
     */
    async restoreModelRequestOpts(requestParameters: RestoreModelRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['modelId'] == null) {
            throw new runtime.RequiredError(
                'modelId',
                'Required parameter "modelId" was null or undefined when calling restoreModel().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v2/model/{modelId}/restore`;
        urlPath = urlPath.replace('{modelId}', encodeURIComponent(String(requestParameters['modelId'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Subject-Restriction: __backend__.
     * Restore a soft-deleted model.
     */
    async restoreModelRaw(requestParameters: RestoreModelRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResDeleteModel>> {
        const requestOptions = await this.restoreModelRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Subject-Restriction: __backend__.
     * Restore a soft-deleted model.
     */
    async restoreModel(modelId: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResDeleteModel> {
        const response = await this.restoreModelRaw({ modelId: modelId }, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateModel without sending the request
     */
    async updateModelRequestOpts(requestParameters: UpdateModelRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['modelId'] == null) {
            throw new runtime.RequiredError(
                'modelId',
                'Required parameter "modelId" was null or undefined when calling updateModel().'
            );
        }

        if (requestParameters['reqModel'] == null) {
            throw new runtime.RequiredError(
                'reqModel',
                'Required parameter "reqModel" was null or undefined when calling updateModel().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v2/model/{modelId}`;
        urlPath = urlPath.replace('{modelId}', encodeURIComponent(String(requestParameters['modelId'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['reqModel'],
        };
    }

    /**
     * Permissions: * `setting.auth.ticket.get.*` - optional: adds _settings.auth.ticket_ to response. * `setting.auth.token.get.*` - optional: adds _settings.auth.token_ to response. * `setting.compute.get.*` - optional: adds _settings.compute_ to response. * `file.upload` - optional: adds _file.upload_ to response. * `file.download` - optional: adds _file.download_ to response. * `get.statistic.*` - optional: adds _statistic_ to response.
     * Update model.
     */
    async updateModelRaw(requestParameters: UpdateModelRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResUpdateModel>> {
        const requestOptions = await this.updateModelRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Permissions: * `setting.auth.ticket.get.*` - optional: adds _settings.auth.ticket_ to response. * `setting.auth.token.get.*` - optional: adds _settings.auth.token_ to response. * `setting.compute.get.*` - optional: adds _settings.compute_ to response. * `file.upload` - optional: adds _file.upload_ to response. * `file.download` - optional: adds _file.download_ to response. * `get.statistic.*` - optional: adds _statistic_ to response.
     * Update model.
     */
    async updateModel(modelId: string, reqModel: ReqModel, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResUpdateModel> {
        const response = await this.updateModelRaw({ modelId: modelId, reqModel: reqModel }, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateModelConfig without sending the request
     */
    async updateModelConfigRequestOpts(requestParameters: UpdateModelConfigRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['modelId'] == null) {
            throw new runtime.RequiredError(
                'modelId',
                'Required parameter "modelId" was null or undefined when calling updateModelConfig().'
            );
        }

        if (requestParameters['reqConfigure'] == null) {
            throw new runtime.RequiredError(
                'reqConfigure',
                'Required parameter "reqConfigure" was null or undefined when calling updateModelConfig().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v2/model/{modelId}/config`;
        urlPath = urlPath.replace('{modelId}', encodeURIComponent(String(requestParameters['modelId'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['reqConfigure'],
        };
    }

    /**
     * Updating the model configuration requires _model authoring privilege_.  Permissions: * `setting.viewer.set.*` - __required__.
     * Update model config.
     */
    async updateModelConfigRaw(requestParameters: UpdateModelConfigRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResUpdateModelConfig>> {
        const requestOptions = await this.updateModelConfigRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Updating the model configuration requires _model authoring privilege_.  Permissions: * `setting.viewer.set.*` - __required__.
     * Update model config.
     */
    async updateModelConfig(modelId: string, reqConfigure: ReqConfigure, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResUpdateModelConfig> {
        const response = await this.updateModelConfigRaw({ modelId: modelId, reqConfigure: reqConfigure }, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateParameterDefaultValues without sending the request
     */
    async updateParameterDefaultValuesRequestOpts(requestParameters: UpdateParameterDefaultValuesRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['modelId'] == null) {
            throw new runtime.RequiredError(
                'modelId',
                'Required parameter "modelId" was null or undefined when calling updateParameterDefaultValues().'
            );
        }

        if (requestParameters['reqCustomization'] == null) {
            throw new runtime.RequiredError(
                'reqCustomization',
                'Required parameter "reqCustomization" was null or undefined when calling updateParameterDefaultValues().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['ignoreUnknownParams'] != null) {
            queryParameters['ignoreUnknownParams'] = requestParameters['ignoreUnknownParams'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v2/model/{modelId}/parameter/defval`;
        urlPath = urlPath.replace('{modelId}', encodeURIComponent(String(requestParameters['modelId'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['reqCustomization'],
        };
    }

    /**
     * Updating default parameter values requires model authoring privilege.  Permissions: * `set.parameter.defval` - __required__.
     * Update default value of parameters.
     */
    async updateParameterDefaultValuesRaw(requestParameters: UpdateParameterDefaultValuesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResUpdateParameterDefaultValues>> {
        const requestOptions = await this.updateParameterDefaultValuesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Updating default parameter values requires model authoring privilege.  Permissions: * `set.parameter.defval` - __required__.
     * Update default value of parameters.
     */
    async updateParameterDefaultValues(modelId: string, reqCustomization: ReqCustomization, ignoreUnknownParams?: boolean, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResUpdateParameterDefaultValues> {
        const response = await this.updateParameterDefaultValuesRaw({ modelId: modelId, reqCustomization: reqCustomization, ignoreUnknownParams: ignoreUnknownParams }, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateParameterDefinitions without sending the request
     */
    async updateParameterDefinitionsRequestOpts(requestParameters: UpdateParameterDefinitionsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['modelId'] == null) {
            throw new runtime.RequiredError(
                'modelId',
                'Required parameter "modelId" was null or undefined when calling updateParameterDefinitions().'
            );
        }

        if (requestParameters['reqParameterDefinitions'] == null) {
            throw new runtime.RequiredError(
                'reqParameterDefinitions',
                'Required parameter "reqParameterDefinitions" was null or undefined when calling updateParameterDefinitions().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v2/model/{modelId}/parameter`;
        urlPath = urlPath.replace('{modelId}', encodeURIComponent(String(requestParameters['modelId'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['reqParameterDefinitions'],
        };
    }

    /**
     * Permissions: * `set.parameter.ui` - __required__.
     * Update definition of parameters.
     */
    async updateParameterDefinitionsRaw(requestParameters: UpdateParameterDefinitionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResUpdateParameterDefinitions>> {
        const requestOptions = await this.updateParameterDefinitionsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Permissions: * `set.parameter.ui` - __required__.
     * Update definition of parameters.
     */
    async updateParameterDefinitions(modelId: string, reqParameterDefinitions: ReqParameterDefinitions, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResUpdateParameterDefinitions> {
        const response = await this.updateParameterDefinitionsRaw({ modelId: modelId, reqParameterDefinitions: reqParameterDefinitions }, initOverrides);
        return await response.value();
    }

}
