/* tslint:disable */
/* eslint-disable */
/**
 * Geometry Backend API v2
 * The ShapeDiver Geometry Backend system is used to: * host Grasshopper models in a secure, reliable, scalable, and performant way, * run computations of Grasshopper models, * and cache and output the results of computations and exports.
 *
 * The version of the OpenAPI document: 2.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import { BaseAPI } from '../../base';
import type {
    QueryComputationStatus,
    ReqCache,
    ReqCustomization,
    ReqCustomizationOrCache,
    ReqOutputDefinitions,
    ResComputeOutputs,
    ResError,
    ResGetCachedOutputs,
    ResListOutputVersions,
    ResUpdateOutputDefinitions,
} from '../models/index';

export interface ComputeOutputsRequest {
    sessionId: string;
    reqCustomization: ReqCustomization;
    ignoreUnknownParams?: boolean;
}

export interface GetCachedOutputsRequest {
    sessionId: string;
    reqCacheReqCustomization: ReqCache | ReqCustomization | null;
}

export interface ListOutputVersionsRequest {
    sessionId: string;
    outputId: string;
    statusComputation?: QueryComputationStatus;
    statusCollect?: QueryComputationStatus;
    offset?: string;
}

export interface UpdateOutputDefinitionsRequest {
    modelId: string;
    reqOutputDefinitions: ReqOutputDefinitions;
}

/**
 * 
 */
export class OutputApi extends BaseAPI {

    /**
     * Creates request options for computeOutputs without sending the request
     */
    async computeOutputsRequestOpts(requestParameters: ComputeOutputsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['sessionId'] == null) {
            throw new runtime.RequiredError(
                'sessionId',
                'Required parameter "sessionId" was null or undefined when calling computeOutputs().'
            );
        }

        if (requestParameters['reqCustomization'] == null) {
            throw new runtime.RequiredError(
                'reqCustomization',
                'Required parameter "reqCustomization" was null or undefined when calling computeOutputs().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['ignoreUnknownParams'] != null) {
            queryParameters['ignoreUnknownParams'] = requestParameters['ignoreUnknownParams'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v2/session/{sessionId}/output`;
        urlPath = urlPath.replace('{sessionId}', encodeURIComponent(String(requestParameters['sessionId'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['reqCustomization'],
        };
    }

    /**
     * Permissions: * `compute.output.*` - __required__.
     * Compute all outputs for given parameter values.
     */
    async computeOutputsRaw(requestParameters: ComputeOutputsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResComputeOutputs>> {
        const requestOptions = await this.computeOutputsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Permissions: * `compute.output.*` - __required__.
     * Compute all outputs for given parameter values.
     */
    async computeOutputs(sessionId: string, reqCustomization: ReqCustomization, ignoreUnknownParams?: boolean, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResComputeOutputs> {
        const response = await this.computeOutputsRaw({ sessionId: sessionId, reqCustomization: reqCustomization, ignoreUnknownParams: ignoreUnknownParams }, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getCachedOutputs without sending the request
     */
    async getCachedOutputsRequestOpts(requestParameters: GetCachedOutputsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['sessionId'] == null) {
            throw new runtime.RequiredError(
                'sessionId',
                'Required parameter "sessionId" was null or undefined when calling getCachedOutputs().'
            );
        }

        if (requestParameters['reqCacheReqCustomization'] === undefined) {
            throw new runtime.RequiredError(
                'reqCacheReqCustomization',
                'Required parameter "reqCacheReqCustomization" was undefined when calling getCachedOutputs().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v2/session/{sessionId}/output/cache`;
        urlPath = urlPath.replace('{sessionId}', encodeURIComponent(String(requestParameters['sessionId'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['reqCacheReqCustomization'],
        };
    }

    /**
     * Permissions: * `cache.output.get.*` - __required__.
     * Get output from cache / check if computation is done.
     */
    async getCachedOutputsRaw(requestParameters: GetCachedOutputsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResGetCachedOutputs>> {
        const requestOptions = await this.getCachedOutputsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Permissions: * `cache.output.get.*` - __required__.
     * Get output from cache / check if computation is done.
     */
    async getCachedOutputs(sessionId: string, reqCacheReqCustomization: ReqCache | ReqCustomization | null, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResGetCachedOutputs> {
        const response = await this.getCachedOutputsRaw({ sessionId: sessionId, reqCacheReqCustomization: reqCacheReqCustomization }, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listOutputVersions without sending the request
     */
    async listOutputVersionsRequestOpts(requestParameters: ListOutputVersionsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['sessionId'] == null) {
            throw new runtime.RequiredError(
                'sessionId',
                'Required parameter "sessionId" was null or undefined when calling listOutputVersions().'
            );
        }

        if (requestParameters['outputId'] == null) {
            throw new runtime.RequiredError(
                'outputId',
                'Required parameter "outputId" was null or undefined when calling listOutputVersions().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['statusComputation'] != null) {
            queryParameters['statusComputation'] = requestParameters['statusComputation'];
        }

        if (requestParameters['statusCollect'] != null) {
            queryParameters['statusCollect'] = requestParameters['statusCollect'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v2/session/{sessionId}/output/{outputId}/list`;
        urlPath = urlPath.replace('{sessionId}', encodeURIComponent(String(requestParameters['sessionId'])));
        urlPath = urlPath.replace('{outputId}', encodeURIComponent(String(requestParameters['outputId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Permissions: * `cache.output.list.*` - __required__.
     * List output versions.
     */
    async listOutputVersionsRaw(requestParameters: ListOutputVersionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResListOutputVersions>> {
        const requestOptions = await this.listOutputVersionsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Permissions: * `cache.output.list.*` - __required__.
     * List output versions.
     */
    async listOutputVersions(sessionId: string, outputId: string, statusComputation?: QueryComputationStatus, statusCollect?: QueryComputationStatus, offset?: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResListOutputVersions> {
        const response = await this.listOutputVersionsRaw({ sessionId: sessionId, outputId: outputId, statusComputation: statusComputation, statusCollect: statusCollect, offset: offset }, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateOutputDefinitions without sending the request
     */
    async updateOutputDefinitionsRequestOpts(requestParameters: UpdateOutputDefinitionsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['modelId'] == null) {
            throw new runtime.RequiredError(
                'modelId',
                'Required parameter "modelId" was null or undefined when calling updateOutputDefinitions().'
            );
        }

        if (requestParameters['reqOutputDefinitions'] == null) {
            throw new runtime.RequiredError(
                'reqOutputDefinitions',
                'Required parameter "reqOutputDefinitions" was null or undefined when calling updateOutputDefinitions().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v2/model/{modelId}/output`;
        urlPath = urlPath.replace('{modelId}', encodeURIComponent(String(requestParameters['modelId'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['reqOutputDefinitions'],
        };
    }

    /**
     * Permissions: * `set.output.ui` - __required__.
     * Update definition of outputs.
     */
    async updateOutputDefinitionsRaw(requestParameters: UpdateOutputDefinitionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResUpdateOutputDefinitions>> {
        const requestOptions = await this.updateOutputDefinitionsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Permissions: * `set.output.ui` - __required__.
     * Update definition of outputs.
     */
    async updateOutputDefinitions(modelId: string, reqOutputDefinitions: ReqOutputDefinitions, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResUpdateOutputDefinitions> {
        const response = await this.updateOutputDefinitionsRaw({ modelId: modelId, reqOutputDefinitions: reqOutputDefinitions }, initOverrides);
        return await response.value();
    }

}
