/* tslint:disable */
/* eslint-disable */
/**
 * Geometry Backend API v2
 * The ShapeDiver Geometry Backend system is used to: * host Grasshopper models in a secure, reliable, scalable, and performant way, * run computations of Grasshopper models, * and cache and output the results of computations and exports.
 *
 * The version of the OpenAPI document: 2.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import { BaseAPI } from '../../base';
import type {
    ResError,
} from '../models/index';

export interface ConfirmScriptRequest {
    scriptId: string;
}

export interface DenyScriptRequest {
    scriptId: string;
}

/**
 * 
 */
export class ScriptApi extends BaseAPI {

    /**
     * Creates request options for confirmScript without sending the request
     */
    async confirmScriptRequestOpts(requestParameters: ConfirmScriptRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['scriptId'] == null) {
            throw new runtime.RequiredError(
                'scriptId',
                'Required parameter "scriptId" was null or undefined when calling confirmScript().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/api/v2/script/{scriptId}/confirm`;
        urlPath = urlPath.replace('{scriptId}', encodeURIComponent(String(requestParameters['scriptId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Permissions: * `script.confirm.*` - __required__.
     * Confirm script.
     */
    async confirmScriptRaw(requestParameters: ConfirmScriptRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        const requestOptions = await this.confirmScriptRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Permissions: * `script.confirm.*` - __required__.
     * Confirm script.
     */
    async confirmScript(scriptId: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.confirmScriptRaw({ scriptId: scriptId }, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for denyScript without sending the request
     */
    async denyScriptRequestOpts(requestParameters: DenyScriptRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['scriptId'] == null) {
            throw new runtime.RequiredError(
                'scriptId',
                'Required parameter "scriptId" was null or undefined when calling denyScript().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/api/v2/script/{scriptId}/deny`;
        urlPath = urlPath.replace('{scriptId}', encodeURIComponent(String(requestParameters['scriptId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Permissions: * `script.deny.*` - __required__.
     * Deny script.
     */
    async denyScriptRaw(requestParameters: DenyScriptRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        const requestOptions = await this.denyScriptRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Permissions: * `script.deny.*` - __required__.
     * Deny script.
     */
    async denyScript(scriptId: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.denyScriptRaw({ scriptId: scriptId }, initOverrides);
        return await response.value();
    }

}
