/* tslint:disable */
/* eslint-disable */
/**
 * Geometry Backend API v2
 * The ShapeDiver Geometry Backend system is used to: * host Grasshopper models in a secure, reliable, scalable, and performant way, * run computations of Grasshopper models, * and cache and output the results of computations and exports.
 *
 * The version of the OpenAPI document: 2.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import { BaseAPI } from '../../base';
import type {
    ReqSdtfDefinition,
    ResDeleteSdtf,
    ResError,
    ResListSdtfs,
    ResUploadSdtf,
} from '../models/index';

export interface DeleteSdtfRequest {
    sessionId: string;
    namespace: string;
    sdtfId: string;
}

export interface DownloadSdtfRequest {
    sessionId: string;
    namespace: string;
    sdtfId: string;
}

export interface ListSdtfsRequest {
    sessionId: string;
    namespace: string;
    offset?: string;
}

export interface UploadSdtfRequest {
    sessionId: string;
    reqSdtfDefinition: Array<ReqSdtfDefinition>;
}

/**
 * 
 */
export class SdtfApi extends BaseAPI {

    /**
     * Creates request options for deleteSdtf without sending the request
     */
    async deleteSdtfRequestOpts(requestParameters: DeleteSdtfRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['sessionId'] == null) {
            throw new runtime.RequiredError(
                'sessionId',
                'Required parameter "sessionId" was null or undefined when calling deleteSdtf().'
            );
        }

        if (requestParameters['namespace'] == null) {
            throw new runtime.RequiredError(
                'namespace',
                'Required parameter "namespace" was null or undefined when calling deleteSdtf().'
            );
        }

        if (requestParameters['sdtfId'] == null) {
            throw new runtime.RequiredError(
                'sdtfId',
                'Required parameter "sdtfId" was null or undefined when calling deleteSdtf().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v2/session/{sessionId}/sdtf/{namespace}/{sdtfId}`;
        urlPath = urlPath.replace('{sessionId}', encodeURIComponent(String(requestParameters['sessionId'])));
        urlPath = urlPath.replace('{namespace}', encodeURIComponent(String(requestParameters['namespace'])));
        urlPath = urlPath.replace('{sdtfId}', encodeURIComponent(String(requestParameters['sdtfId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Permissions: * `asset.sdtf.delete.*` - __required__.
     * Delete a sdTF-assets.
     */
    async deleteSdtfRaw(requestParameters: DeleteSdtfRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResDeleteSdtf>> {
        const requestOptions = await this.deleteSdtfRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Permissions: * `asset.sdtf.delete.*` - __required__.
     * Delete a sdTF-assets.
     */
    async deleteSdtf(sessionId: string, namespace: string, sdtfId: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResDeleteSdtf> {
        const response = await this.deleteSdtfRaw({ sessionId: sessionId, namespace: namespace, sdtfId: sdtfId }, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for downloadSdtf without sending the request
     */
    async downloadSdtfRequestOpts(requestParameters: DownloadSdtfRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['sessionId'] == null) {
            throw new runtime.RequiredError(
                'sessionId',
                'Required parameter "sessionId" was null or undefined when calling downloadSdtf().'
            );
        }

        if (requestParameters['namespace'] == null) {
            throw new runtime.RequiredError(
                'namespace',
                'Required parameter "namespace" was null or undefined when calling downloadSdtf().'
            );
        }

        if (requestParameters['sdtfId'] == null) {
            throw new runtime.RequiredError(
                'sdtfId',
                'Required parameter "sdtfId" was null or undefined when calling downloadSdtf().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v2/session/{sessionId}/sdtf/{namespace}/{sdtfId}`;
        urlPath = urlPath.replace('{sessionId}', encodeURIComponent(String(requestParameters['sessionId'])));
        urlPath = urlPath.replace('{namespace}', encodeURIComponent(String(requestParameters['namespace'])));
        urlPath = urlPath.replace('{sdtfId}', encodeURIComponent(String(requestParameters['sdtfId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Permissions: * `asset.sdtf.get.*` - __required__.
     * Download a sdTF-asset.
     */
    async downloadSdtfRaw(requestParameters: DownloadSdtfRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Blob>> {
        const requestOptions = await this.downloadSdtfRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.BlobApiResponse(response);
    }

    /**
     * Permissions: * `asset.sdtf.get.*` - __required__.
     * Download a sdTF-asset.
     */
    async downloadSdtf(sessionId: string, namespace: string, sdtfId: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Blob> {
        const response = await this.downloadSdtfRaw({ sessionId: sessionId, namespace: namespace, sdtfId: sdtfId }, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listSdtfs without sending the request
     */
    async listSdtfsRequestOpts(requestParameters: ListSdtfsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['sessionId'] == null) {
            throw new runtime.RequiredError(
                'sessionId',
                'Required parameter "sessionId" was null or undefined when calling listSdtfs().'
            );
        }

        if (requestParameters['namespace'] == null) {
            throw new runtime.RequiredError(
                'namespace',
                'Required parameter "namespace" was null or undefined when calling listSdtfs().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v2/session/{sessionId}/sdtf/{namespace}/list`;
        urlPath = urlPath.replace('{sessionId}', encodeURIComponent(String(requestParameters['sessionId'])));
        urlPath = urlPath.replace('{namespace}', encodeURIComponent(String(requestParameters['namespace'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Permissions: * `asset.sdtf.list.*` - __required__.
     * List all sdTF-assets of a namespace.
     */
    async listSdtfsRaw(requestParameters: ListSdtfsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResListSdtfs>> {
        const requestOptions = await this.listSdtfsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Permissions: * `asset.sdtf.list.*` - __required__.
     * List all sdTF-assets of a namespace.
     */
    async listSdtfs(sessionId: string, namespace: string, offset?: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResListSdtfs> {
        const response = await this.listSdtfsRaw({ sessionId: sessionId, namespace: namespace, offset: offset }, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for uploadSdtf without sending the request
     */
    async uploadSdtfRequestOpts(requestParameters: UploadSdtfRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['sessionId'] == null) {
            throw new runtime.RequiredError(
                'sessionId',
                'Required parameter "sessionId" was null or undefined when calling uploadSdtf().'
            );
        }

        if (requestParameters['reqSdtfDefinition'] == null) {
            throw new runtime.RequiredError(
                'reqSdtfDefinition',
                'Required parameter "reqSdtfDefinition" was null or undefined when calling uploadSdtf().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v2/session/{sessionId}/sdtf/upload`;
        urlPath = urlPath.replace('{sessionId}', encodeURIComponent(String(requestParameters['sessionId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['reqSdtfDefinition'],
        };
    }

    /**
     * Permissions: * `asset.sdtf.create.*` - __required__.
     * Request upload URL for a sdTF-asset.
     */
    async uploadSdtfRaw(requestParameters: UploadSdtfRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResUploadSdtf>> {
        const requestOptions = await this.uploadSdtfRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Permissions: * `asset.sdtf.create.*` - __required__.
     * Request upload URL for a sdTF-asset.
     */
    async uploadSdtf(sessionId: string, reqSdtfDefinition: Array<ReqSdtfDefinition>, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResUploadSdtf> {
        const response = await this.uploadSdtfRaw({ sessionId: sessionId, reqSdtfDefinition: reqSdtfDefinition }, initOverrides);
        return await response.value();
    }

}
