/* tslint:disable */
/* eslint-disable */
/**
 * Geometry Backend API v2
 * The ShapeDiver Geometry Backend system is used to: * host Grasshopper models in a secure, reliable, scalable, and performant way, * run computations of Grasshopper models, * and cache and output the results of computations and exports.
 *
 * The version of the OpenAPI document: 2.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import { BaseAPI } from '../../base';
import type {
    ReqCustomizationOrExport,
    ReqTicket,
    ResCloseSession,
    ResCreateSessionByModel,
    ResCreateSessionByTicket,
    ResCreateTicket,
    ResDecryptTicket,
    ResError,
    ResGetSessionDefaults,
} from '../models/index';

export interface CloseSessionRequest {
    sessionId: string;
}

export interface CreateSessionByModelRequest {
    modelId: string;
    modelStateId?: string;
    ignoreUnknownParams?: boolean;
    strictModelStateValidation?: boolean;
    reqCustomizationOrExport?: ReqCustomizationOrExport;
}

export interface CreateSessionByTicketRequest {
    ticketId: string;
    modelStateId?: string;
    ignoreUnknownParams?: boolean;
    strictModelStateValidation?: boolean;
    reqCustomizationOrExport?: ReqCustomizationOrExport;
}

export interface CreateTicketRequest {
    modelId: string;
    reqTicket: ReqTicket;
}

export interface DecryptTicketRequest {
    ticketEncrypted: string;
}

export interface GetSessionDefaultsRequest {
    sessionId: string;
}

/**
 * 
 */
export class SessionApi extends BaseAPI {

    /**
     * Creates request options for closeSession without sending the request
     */
    async closeSessionRequestOpts(requestParameters: CloseSessionRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['sessionId'] == null) {
            throw new runtime.RequiredError(
                'sessionId',
                'Required parameter "sessionId" was null or undefined when calling closeSession().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v2/session/{sessionId}/close`;
        urlPath = urlPath.replace('{sessionId}', encodeURIComponent(String(requestParameters['sessionId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Close session.
     */
    async closeSessionRaw(requestParameters: CloseSessionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResCloseSession>> {
        const requestOptions = await this.closeSessionRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Close session.
     */
    async closeSession(sessionId: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResCloseSession> {
        const response = await this.closeSessionRaw({ sessionId: sessionId }, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createSessionByModel without sending the request
     */
    async createSessionByModelRequestOpts(requestParameters: CreateSessionByModelRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['modelId'] == null) {
            throw new runtime.RequiredError(
                'modelId',
                'Required parameter "modelId" was null or undefined when calling createSessionByModel().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['modelStateId'] != null) {
            queryParameters['modelStateId'] = requestParameters['modelStateId'];
        }

        if (requestParameters['ignoreUnknownParams'] != null) {
            queryParameters['ignoreUnknownParams'] = requestParameters['ignoreUnknownParams'];
        }

        if (requestParameters['strictModelStateValidation'] != null) {
            queryParameters['strictModelStateValidation'] = requestParameters['strictModelStateValidation'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v2/model/{modelId}/session`;
        urlPath = urlPath.replace('{modelId}', encodeURIComponent(String(requestParameters['modelId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['reqCustomizationOrExport'],
        };
    }

    /**
     * Permissions: * `auth.session` - __required__. * `get.parameter.*` - optional: adds _parameters_ to response. * Output:   * If body contains a computation request: `compute.output.*` - __required__.   * If no computation request: `compute.output.*` - optional: adds _output for default     parameter_ to response.   * otherwise tries: `get.output.*` - optional: adds _output definitions_ to response. * Export:   * Body contains an export request: `compute.export.*` - __required__.   * No export request: `get.export.*` - optional: adds _export definitions_ to response.
     * Initialize new session by model ID.
     */
    async createSessionByModelRaw(requestParameters: CreateSessionByModelRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResCreateSessionByModel>> {
        const requestOptions = await this.createSessionByModelRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Permissions: * `auth.session` - __required__. * `get.parameter.*` - optional: adds _parameters_ to response. * Output:   * If body contains a computation request: `compute.output.*` - __required__.   * If no computation request: `compute.output.*` - optional: adds _output for default     parameter_ to response.   * otherwise tries: `get.output.*` - optional: adds _output definitions_ to response. * Export:   * Body contains an export request: `compute.export.*` - __required__.   * No export request: `get.export.*` - optional: adds _export definitions_ to response.
     * Initialize new session by model ID.
     */
    async createSessionByModel(modelId: string, modelStateId?: string, ignoreUnknownParams?: boolean, strictModelStateValidation?: boolean, reqCustomizationOrExport?: ReqCustomizationOrExport, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResCreateSessionByModel> {
        const response = await this.createSessionByModelRaw({ modelId: modelId, modelStateId: modelStateId, ignoreUnknownParams: ignoreUnknownParams, strictModelStateValidation: strictModelStateValidation, reqCustomizationOrExport: reqCustomizationOrExport }, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createSessionByTicket without sending the request
     */
    async createSessionByTicketRequestOpts(requestParameters: CreateSessionByTicketRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['ticketId'] == null) {
            throw new runtime.RequiredError(
                'ticketId',
                'Required parameter "ticketId" was null or undefined when calling createSessionByTicket().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['modelStateId'] != null) {
            queryParameters['modelStateId'] = requestParameters['modelStateId'];
        }

        if (requestParameters['ignoreUnknownParams'] != null) {
            queryParameters['ignoreUnknownParams'] = requestParameters['ignoreUnknownParams'];
        }

        if (requestParameters['strictModelStateValidation'] != null) {
            queryParameters['strictModelStateValidation'] = requestParameters['strictModelStateValidation'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v2/ticket/{ticketId}`;
        urlPath = urlPath.replace('{ticketId}', encodeURIComponent(String(requestParameters['ticketId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['reqCustomizationOrExport'],
        };
    }

    /**
     * Permissions: * `get.parameter.*` - optional: adds _parameters_ to response. * Output:   * If body contains a computation request: `compute.output.*` - __required__.   * If no computation request: `compute.output.*` - optional: adds _output for default     parameter_ to response.   * otherwise tries: `get.output.*` - optional: adds _output definitions_ to response. * Export:   * Body contains an export request: `compute.export.*` - __required__.   * No export request: `get.export.*` - optional: adds _export definitions_ to response.
     * Initialize new session by ticket.
     */
    async createSessionByTicketRaw(requestParameters: CreateSessionByTicketRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResCreateSessionByTicket>> {
        const requestOptions = await this.createSessionByTicketRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Permissions: * `get.parameter.*` - optional: adds _parameters_ to response. * Output:   * If body contains a computation request: `compute.output.*` - __required__.   * If no computation request: `compute.output.*` - optional: adds _output for default     parameter_ to response.   * otherwise tries: `get.output.*` - optional: adds _output definitions_ to response. * Export:   * Body contains an export request: `compute.export.*` - __required__.   * No export request: `get.export.*` - optional: adds _export definitions_ to response.
     * Initialize new session by ticket.
     */
    async createSessionByTicket(ticketId: string, modelStateId?: string, ignoreUnknownParams?: boolean, strictModelStateValidation?: boolean, reqCustomizationOrExport?: ReqCustomizationOrExport, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResCreateSessionByTicket> {
        const response = await this.createSessionByTicketRaw({ ticketId: ticketId, modelStateId: modelStateId, ignoreUnknownParams: ignoreUnknownParams, strictModelStateValidation: strictModelStateValidation, reqCustomizationOrExport: reqCustomizationOrExport }, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createTicket without sending the request
     */
    async createTicketRequestOpts(requestParameters: CreateTicketRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['modelId'] == null) {
            throw new runtime.RequiredError(
                'modelId',
                'Required parameter "modelId" was null or undefined when calling createTicket().'
            );
        }

        if (requestParameters['reqTicket'] == null) {
            throw new runtime.RequiredError(
                'reqTicket',
                'Required parameter "reqTicket" was null or undefined when calling createTicket().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v2/model/{modelId}/ticket`;
        urlPath = urlPath.replace('{modelId}', encodeURIComponent(String(requestParameters['modelId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['reqTicket'],
        };
    }

    /**
     * Subject-Restriction: __backend__.  Permissions: * `setting.auth.ticket.create.*` - __required__. * `setting.auth.ticket.get.*` - optional: adds _settings.auth.ticket_ to response. * `setting.auth.token.get.*` - optional: adds _settings.auth.token_ to response. * `setting.compute.get.*` - optional: adds _settings.compute_ to response. * `file.upload` - optional: adds _file.upload_ to response. * `file.download` - optional: adds _file.download_ to response. * `get.statistic.*` - optional: adds _statistic_ to response.
     * Create a new ticket that allows to initialize a new session.
     */
    async createTicketRaw(requestParameters: CreateTicketRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResCreateTicket>> {
        const requestOptions = await this.createTicketRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Subject-Restriction: __backend__.  Permissions: * `setting.auth.ticket.create.*` - __required__. * `setting.auth.ticket.get.*` - optional: adds _settings.auth.ticket_ to response. * `setting.auth.token.get.*` - optional: adds _settings.auth.token_ to response. * `setting.compute.get.*` - optional: adds _settings.compute_ to response. * `file.upload` - optional: adds _file.upload_ to response. * `file.download` - optional: adds _file.download_ to response. * `get.statistic.*` - optional: adds _statistic_ to response.
     * Create a new ticket that allows to initialize a new session.
     */
    async createTicket(modelId: string, reqTicket: ReqTicket, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResCreateTicket> {
        const response = await this.createTicketRaw({ modelId: modelId, reqTicket: reqTicket }, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for decryptTicket without sending the request
     */
    async decryptTicketRequestOpts(requestParameters: DecryptTicketRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['ticketEncrypted'] == null) {
            throw new runtime.RequiredError(
                'ticketEncrypted',
                'Required parameter "ticketEncrypted" was null or undefined when calling decryptTicket().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v2/ticket/{ticketEncrypted}`;
        urlPath = urlPath.replace('{ticketEncrypted}', encodeURIComponent(String(requestParameters['ticketEncrypted'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Subject-Restriction: __backend__.  Permissions: * `setting.auth.ticket.decrypt.*` - __required__.
     * Decrypt the given ticket and return its details.
     */
    async decryptTicketRaw(requestParameters: DecryptTicketRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResDecryptTicket>> {
        const requestOptions = await this.decryptTicketRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Subject-Restriction: __backend__.  Permissions: * `setting.auth.ticket.decrypt.*` - __required__.
     * Decrypt the given ticket and return its details.
     */
    async decryptTicket(ticketEncrypted: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResDecryptTicket> {
        const response = await this.decryptTicketRaw({ ticketEncrypted: ticketEncrypted }, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getSessionDefaults without sending the request
     */
    async getSessionDefaultsRequestOpts(requestParameters: GetSessionDefaultsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['sessionId'] == null) {
            throw new runtime.RequiredError(
                'sessionId',
                'Required parameter "sessionId" was null or undefined when calling getSessionDefaults().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v2/session/{sessionId}/default`;
        urlPath = urlPath.replace('{sessionId}', encodeURIComponent(String(requestParameters['sessionId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Permissions: * `get.parameter.*` - optional: adds _parameter defaults_ to response. * `get.export.*` - optional: adds _export definitions_ to response. * `compute.output.*` - optional: adds _outputs for default parameters_ to response. * `get.output.*` - optional: adds _output definitions_ to response.
     * Get session defaults (corresponds to the content of the session initialization request).
     */
    async getSessionDefaultsRaw(requestParameters: GetSessionDefaultsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResGetSessionDefaults>> {
        const requestOptions = await this.getSessionDefaultsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Permissions: * `get.parameter.*` - optional: adds _parameter defaults_ to response. * `get.export.*` - optional: adds _export definitions_ to response. * `compute.output.*` - optional: adds _outputs for default parameters_ to response. * `get.output.*` - optional: adds _output definitions_ to response.
     * Get session defaults (corresponds to the content of the session initialization request).
     */
    async getSessionDefaults(sessionId: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResGetSessionDefaults> {
        const response = await this.getSessionDefaultsRaw({ sessionId: sessionId }, initOverrides);
        return await response.value();
    }

}
