/* tslint:disable */
/* eslint-disable */
/**
 * Geometry Backend API v2
 * The ShapeDiver Geometry Backend system is used to: * host Grasshopper models in a secure, reliable, scalable, and performant way, * run computations of Grasshopper models, * and cache and output the results of computations and exports.
 *
 * The version of the OpenAPI document: 2.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import { BaseAPI } from '../../base';
import type {
    ResDeleteModel,
    ResError,
    ResGetMinionsInfo,
    ResGetScaleInCandidate,
    ResGetWorkersInfo,
} from '../models/index';

export interface CreateSignedUrlRequest {
    endpoint: string;
    encodedUri: string;
}

export interface EraseModelRequest {
    modelId: string;
}

/**
 * 
 */
export class SystemApi extends BaseAPI {

    /**
     * Creates request options for createSignedUrl without sending the request
     */
    async createSignedUrlRequestOpts(requestParameters: CreateSignedUrlRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['endpoint'] == null) {
            throw new runtime.RequiredError(
                'endpoint',
                'Required parameter "endpoint" was null or undefined when calling createSignedUrl().'
            );
        }

        if (requestParameters['encodedUri'] == null) {
            throw new runtime.RequiredError(
                'encodedUri',
                'Required parameter "encodedUri" was null or undefined when calling createSignedUrl().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v2/system/sign/cdn/{endpoint}/{encodedUri}`;
        urlPath = urlPath.replace('{endpoint}', encodeURIComponent(String(requestParameters['endpoint'])));
        urlPath = urlPath.replace('{encodedUri}', encodeURIComponent(String(requestParameters['encodedUri'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Subject-Restriction: __backend__.
     * Create a signed URL for the specified endpoint and target.
     */
    async createSignedUrlRaw(requestParameters: CreateSignedUrlRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        const requestOptions = await this.createSignedUrlRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Subject-Restriction: __backend__.
     * Create a signed URL for the specified endpoint and target.
     */
    async createSignedUrl(endpoint: string, encodedUri: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.createSignedUrlRaw({ endpoint: endpoint, encodedUri: encodedUri }, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for eraseModel without sending the request
     */
    async eraseModelRequestOpts(requestParameters: EraseModelRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['modelId'] == null) {
            throw new runtime.RequiredError(
                'modelId',
                'Required parameter "modelId" was null or undefined when calling eraseModel().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v2/system/model/{modelId}`;
        urlPath = urlPath.replace('{modelId}', encodeURIComponent(String(requestParameters['modelId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Subject-Restriction: __backend__.  Permissions: * `delete.hard` - __required__.
     * Delete model permanently.
     */
    async eraseModelRaw(requestParameters: EraseModelRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResDeleteModel>> {
        const requestOptions = await this.eraseModelRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Subject-Restriction: __backend__.  Permissions: * `delete.hard` - __required__.
     * Delete model permanently.
     */
    async eraseModel(modelId: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResDeleteModel> {
        const response = await this.eraseModelRaw({ modelId: modelId }, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getMinionsInfo without sending the request
     */
    async getMinionsInfoRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/api/v2/system/minions/info`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Subject-Restriction: __backend__.
     * Get system information about the Geometry Minions.
     */
    async getMinionsInfoRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResGetMinionsInfo>> {
        const requestOptions = await this.getMinionsInfoRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Subject-Restriction: __backend__.
     * Get system information about the Geometry Minions.
     */
    async getMinionsInfo(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResGetMinionsInfo> {
        const response = await this.getMinionsInfoRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getScaleInCandidate without sending the request
     */
    async getScaleInCandidateRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/api/v2/system/workers/scale-in-candidate`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get a Geometry Worker that is a candidate for scaling in.
     */
    async getScaleInCandidateRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResGetScaleInCandidate>> {
        const requestOptions = await this.getScaleInCandidateRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Get a Geometry Worker that is a candidate for scaling in.
     */
    async getScaleInCandidate(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResGetScaleInCandidate> {
        const response = await this.getScaleInCandidateRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getWorkersInfo without sending the request
     */
    async getWorkersInfoRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/api/v2/system/workers/info`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * A __backend__ subject adds `system.plugins.inconsistent`.
     * Get system information about the Geometry Workers.
     */
    async getWorkersInfoRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResGetWorkersInfo>> {
        const requestOptions = await this.getWorkersInfoRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * A __backend__ subject adds `system.plugins.inconsistent`.
     * Get system information about the Geometry Workers.
     */
    async getWorkersInfo(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResGetWorkersInfo> {
        const response = await this.getWorkersInfoRaw(initOverrides);
        return await response.value();
    }

}
