/* tslint:disable */
/* eslint-disable */
/**
 * Geometry Backend API v2
 * The ShapeDiver Geometry Backend system is used to: * host Grasshopper models in a secure, reliable, scalable, and performant way, * run computations of Grasshopper models, * and cache and output the results of computations and exports.
 *
 * The version of the OpenAPI document: 2.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import { BaseAPI } from '../../base';
import type {
    ResError,
    ResListTextures,
} from '../models/index';

export interface ListTexturesRequest {
    sessionId: string;
    offset?: string;
}

/**
 * 
 */
export class TextureApi extends BaseAPI {

    /**
     * Creates request options for listTextures without sending the request
     */
    async listTexturesRequestOpts(requestParameters: ListTexturesRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['sessionId'] == null) {
            throw new runtime.RequiredError(
                'sessionId',
                'Required parameter "sessionId" was null or undefined when calling listTextures().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JwtAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v2/session/{sessionId}/texture/list`;
        urlPath = urlPath.replace('{sessionId}', encodeURIComponent(String(requestParameters['sessionId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Permissions: * `cache.texture.list.*` - __required__.
     * List model textures.
     */
    async listTexturesRaw(requestParameters: ListTexturesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResListTextures>> {
        const requestOptions = await this.listTexturesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Permissions: * `cache.texture.list.*` - __required__.
     * List model textures.
     */
    async listTextures(sessionId: string, offset?: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResListTextures> {
        const response = await this.listTexturesRaw({ sessionId: sessionId, offset: offset }, initOverrides);
        return await response.value();
    }

}
